### ISSUE TITLE
FYI Linux mint 17.2 cinnamon

### ISSUE THREAD

**Issue by erikdubois** [Foggalong/hardcode-fixer#114]
Your scripts fixes these icons in one swift blow.
Just some feed-back and yes it is 17.2 release candidate

G: Fixing Hardinfo...
G: Fixing HP Printer...
G: Fixing Mint Backup...
G: Fixing Mint Drivers...
G: Fixing Python (v2.7)...
G: Fixing Python (v3.4)...

**Comment by Foggalong** [comment]
Good to know! :D
