### ISSUE TITLE
Domain blocker

### ISSUE THREAD

**Issue by erikdubois** [Foggalong/hardcode-fixer#116]
File : /usr/share/applications/mintNanny.desktop

Content of file : 

[Desktop Entry]
Name=Domain Blocker
Name[af]=Domein Blokker
Exec=mintnanny
Icon=/usr/lib/linuxmint/mintNanny/icon.svg
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;System;Settings;
StartupNotify=false
NotShowIn=KDE;

change to

Icon=mintNanny

**Comment by palob** [comment]
Again no Numix-Circle icon with that name.
