### ISSUE TITLE
Software Manager

### ISSUE THREAD

**Issue by erikdubois** [Foggalong/hardcode-fixer#118]
File : /usr/share/applications/mintInstall.desktop

Content of file :

[Desktop Entry]
Name=Software Manager
Exec=gksu mintinstall
Icon=/usr/lib/linuxmint/mintInstall/icon.svg
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;System;Settings
NotShowIn=KDE;

change to

Icon=software-manager

**Comment by palob** [comment]
Again no Numix-Circle icon with that name.
