### ISSUE TITLE
Software Sources

### ISSUE THREAD

**Issue by erikdubois** [Foggalong/hardcode-fixer#119]
File : /usr/share/applications/mintsources.desktop

Content of file :

[Desktop Entry]
Name=Software Sources
Exec=software-sources
Icon=/usr/share/icons/hicolor/scalable/apps/software-sources.svg
Terminal=false
X-MultipleArgs=false
Type=Application
Categories=GNOME;GTK;System;Settings;X-GNOME-SystemSettings;X-GNOME-Settings-Panel;
X-GNOME-Settings-Panel=software-properties
MimeType=text/x-apt-sources-list;
X-KDE-SubstituteUID=true
X-Ubuntu-Gettext-Domain=software-properties
NotShowIn=KDE;

change to

Icon=software-sources

**Comment by palob** [comment]
Again no Numix-Circle icon with that name.
