### ISSUE TITLE
Update manager

### ISSUE THREAD

**Issue by erikdubois** [Foggalong/hardcode-fixer#120]
File : /usr/share/applications/mintUpdate.desktop

Content of file :

[Desktop Entry]
Name=Update Manager
Exec=mintupdate
Icon=/usr/lib/linuxmint/mintUpdate/icons/base.svg
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;System;Settings;
StartupNotify=false

change to

Icon=mintUpdate

**Comment by palob** [comment]
Same here, a Numix-Circle icon/symlink ``mintUpdate.svg`` needs to be created first.
