### ISSUE TITLE
Upload manager

### ISSUE THREAD

**Issue by erikdubois** [Foggalong/hardcode-fixer#122]
File : /usr/share/applications/mintupload.desktop

Content of file :

[Desktop Entry]
Name=Upload Manager
Exec=mintupload-manager
Icon=/usr/lib/linuxmint/mintUpload/icon.svg
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;System;Settings
StartupNotify=false
NotShowIn=KDE

change to

Icon=mintUpload

**Comment by palob** [comment]
But currently there isn't a Numix-Circle icon ``mintUpload.svg``, or is it?

**Comment by erikdubois** [comment]
i was just looking into that. 
i was just thinking of using the names of numix-circle icon as reference.
Give me some time

**Comment by Foggalong** [comment]
@palob @erikdubois Replying here because it's the most recent issue.

There doesn't have to be a Numix icon for an app for it to be included here, Numix just follows the icon conventions set out by this project. That's also the reason it's hosted on my private GitHub, not the Numix one.

**Comment by erikdubois** [comment]
ok understood

**Comment by erikdubois** [comment]
Clean  install 17.2 cinnamon x64
numix circle installed via sudo add-apt-repository ppa:numix/ppa

Which icons do NOT change in /usr/share/applications?

 /usr/share/applications/kde4

Backup Tool 
Domain Blocker
Driver Manager
Software Sources
Upload Manager

/usr/share/applications

Backup Tool (also mime)
Domain Blocker
Driver Manager
Gdebi Package installer
Python v2.7
Python v3.4
reactivate HP Laserjet 1018/1020 after reloading paper
Software Manager
Software Sources
Update Manager
Upload Manager

**Comment by erikdubois** [comment]
Now i will run your script and report back what happens.
