### ISSUE TITLE
Analysis based on Numix circle

### ISSUE THREAD

**Issue by erikdubois** [Foggalong/hardcode-fixer#123]
Clean install 17.2 cinnamon x64
numix circle installed via sudo add-apt-repository ppa:numix/ppa

Which icons do NOT change in /usr/share/applications?

/usr/share/applications/kde4

Backup Tool
Domain Blocker
Driver Manager
Software Sources
Upload Manager

/usr/share/applications

Backup Tool (also mime)
Domain Blocker
Driver Manager
Gdebi Package installer
Python v2.7
Python v3.4
reactivate HP Laserjet 1018/1020 after reloading paper
Software Manager
Software Sources
Update Manager
Upload Manager

Then there is the issue of renaming.

http://i.imgur.com/rE9SmAp.png

**Comment by erikdubois** [comment]
i will run your script now and report back

**Comment by Foggalong** [comment]
The only thing this script does is change is the icon line of the desktop file to something that icon themes can use (for example from `Icon=/usr/lib/linuxmint/mintUpload/icon.svg` to `Icon=mintUpload`) and then copy the default icon from the hardcoded location to `/usr/share/icons/hicolor/` where it can be properly accessed.

This script isn't about themeing the icons selves, that's all down to whatever icon theme you use.

**Comment by erikdubois** [comment]
glad you explained this part

and then copy the default icon from the hardcoded location to /usr/share/icons/hicolor/ where it can be properly accessed.

Otherswise we would have some 'holes'.

**Comment by erikdubois** [comment]
I hope you will see this even when it is closed

feedback 

G: Fixing HP Printer...
G: Fixing Mint Backup...
G: Fixing Mint Backup...
G: Fixing Mint Drivers...
G: Fixing Mint Nanny...
G: Fixing Mint Software Manager...
G: Fixing Mint Software Sources...
G: Fixing Mint Update Manager...
G: Fixing Mint Upload Manager...
G: Fixing Python (v2.7)...
G: Fixing Python (v3.4)...

**Comment by Foggalong** [comment]
That's great to see :D I've added the needed icons to [Circle](https://github.com/numixproject/numix-icon-theme-circle/commit/ec609ae56b2f494077585774b1c501f219f0f07e) too
