### ISSUE TITLE
Analysis based on Numix circle

### ISSUE THREAD

**Issue by erikdubois** [Foggalong/hardcode-fixer#124]
After running your script
using numix circle

This is the output.

G: Fixing HP Printer...
G: Fixing Mint Backup...
G: Fixing Mint Backup...
G: Fixing Mint Drivers...
G: Fixing Mint Nanny...
G: Fixing Mint Software Manager...
G: Fixing Mint Software Sources...
G: Fixing Mint Update Manager...
G: Fixing Mint Upload Manager...
G: Fixing Python (v2.7)...
G: Fixing Python (v3.4)...

Issues yet to be solved 

Backup tool
Domain Blocker
Update manager
Upload Manager

have no icon.

**Comment by Foggalong** [comment]
If you update to the latest version of Circle you'll find them done :)

**Comment by erikdubois** [comment]
ahah I did not read this one.
That's why you reacted the way you did.
