### ISSUE TITLE
updating numix circle

### ISSUE THREAD

**Issue by erikdubois** [Foggalong/hardcode-fixer#125]
i get this as answer

Unpacking numix-icon-theme-circle (1.0.2+3~201502071451~ubuntu14.04.1) over (1.0.2+3~201502071451~ubuntu14.04.1) ...
gtk-update-icon-cache-3.0: The generated cache was invalid.
WARNING: icon cache generation failed for /usr/share/icons/Numix-Circle
gtk-update-icon-cache-3.0: The generated cache was invalid.
WARNING: icon cache generation failed for /usr/share/icons/Numix-Circle-Light
Setting up numix-icon-theme-circle (1.0.2+3~201502071451~ubuntu14.04.1) ...
gtk-update-icon-cache: The generated cache was invalid.

anything I can do?

**Comment by Foggalong** [comment]
duuuuude. stop opening new issues here. This repo isn't for Numix Circle. I'm not sure why the cache is showing up invalid, but it's not something that prevents the theme from being displayed

**Comment by erikdubois** [comment]
sorry just trying to be helpful
may be too helpful

**Comment by Foggalong** [comment]
Not at all, it's just important to reports issues [in the right repo](https://github.com/numixproject/numix-icon-theme-circle) so that the relevant people can see it to fix :)

**Comment by erikdubois** [comment]
I do think we have an issue unrelated to the theming (Numix or other)

I see the old icons have arrived in /usr/share/icons/hicolor/48x48/apps

BUT

they do not show up in the menu's or the /usr/share/applications

I analysed just one. The first one in the menu

Backup tool

/usr/share/applications/mintBackup.desktop points to Icon=mintbackup
and in the folder /usr/share/icons/hicolor/48x48/apps there is the old icon with the name mintbackup

In this folder I see also 
- mintNanny
- mintUpdate
- mintUpload
- software-manager
- software-sources and software-sources.png

All these icons are now missing using either Numix or the normal Mint-x theme.

Which makes a total of 6 icons missing? Should they be placed in an other folder, I wonder.

**Comment by Foggalong** [comment]
Have you made sure your icon cache is updated after updating the theme? Possibly log out and back in again to be sure

**Comment by erikdubois** [comment]
i will reboot

**Comment by erikdubois** [comment]
i rebooted
did 
 sudo gtk-update-icon-cache
and
sudo gtk-update-icon-cache-3.0 
logged off
same icons missing?
