### ISSUE TITLE
Capital letters in two icons

### ISSUE THREAD

**Issue by erikdubois** [Foggalong/hardcode-fixer#126]
Posted this on Numix-circle - I think it might be best it is posted here.
Taking a risk and opening an issue.

Copy/paste text from Numix-circle

mintNanny.desktop file points to Icon=mintnanny
But there is only a mintNanny.svg link.
Change to Icon=mintNanny

Will post this in hardcore-fixer at foggalong. I believe it can be changed there

mintupload.desktop files point to Icon=mintupload
But there is only a mintUpload.svg
Change to Icon=mintUpload

Will post this in hardcore-fixer at foggalong. I believe it can be changed there

**Comment by Foggalong** [comment]
All the icons are correct, both in Circle and here. Is it possible you're still using .desktop files from a previous fixing?

**Comment by erikdubois** [comment]
I must agree that it was not a clean install computer where i noticed the differences...
I will try tomorrow on a clean install.
How can I get the very latest numix-circle icons? How do I install them?

**Comment by Foggalong** [comment]
```bash
git clone https://github.com/numixproject/numix-icon-theme-circle.git
sudo cp -r numix-icon-theme-circle/Numix-Circle /usr/share/icons/
```
And then applying it using your settings manager of choice :)

**Comment by erikdubois** [comment]
I thought I was doing it correctly... Did this and only this no other numix icon themes (inherits...)
Tried also the four folders of numix in the folder ./icons. Did not show up in themes manager.

I am working on a 17.2 cinnamon 64 bits release candidate. 

It does not show up in the themes manager from mint? 

Ardis icon theme does.
Flattr icon theme does.
Flat remix icon theme does.

But it works when I install it via ppa. Then it shows up in the manager. I am missing something.

**Comment by Foggalong** [comment]
No, you need to do that for both Circle and the Base theme if you want both parts

**Comment by erikdubois** [comment]
Last check today
installed clean install linux mint 17.1 x64 cinnamon NOT the release candidate 17.2
installed numix circle
got the latest numix circle from github and pasted it in the /usr/share/icons

ran your script
G: Fixing HP Printer...
G: Fixing Mint Backup...
G: Fixing Mint Backup...
G: Fixing Mint Drivers...
G: Fixing Mint Nanny...
G: Fixing Mint Software Manager...
G: Fixing Mint Software Sources...
G: Fixing Mint Update Manager...
G: Fixing Mint Upload Manager...
G: Fixing Python (v2.7)...
G: Fixing Python (v3.4)...

There are some that are blank and do not have an icon.
http://i.imgur.com/HGnhRkQ.png
