### ISSUE TITLE
not working for jetbrains ide icons

### ISSUE THREAD

**Issue by rahul8290238014** [Foggalong/hardcode-fixer#128]
the fixer not works for jetbrains ides like phpstorm,pycharm , intellijIdea and webstorm in ubuntu 14.04 (64 bit).

**Comment by Foggalong** [comment]
@rahul8290238014 Can you give us the information needed for each to add them to the fix list? The file name for the .desktop launcher and the icon line in the launcher :)

**Comment by rahul8290238014** [comment]
Name of desktop files are :-
(i)  jetbrains-idea.desktop
(ii) jetbrains-phpstorm.desktop
(iii) jetbrains-pycharm.desktop
(iv) jetbrains-webstorm.desktop
 I am using currently these four , for rubymine i guess that the name of .desktop file should be 
(v)  jetbrains-rubymine.desktop


1. IntellijIdea 
 
[Desktop Entry]
Version=1.0
Type=Application
Name=IntelliJ IDEA
//Default Icon path , this is not fixed because it depends the location where user //extract and run the intellijIdea zip( the all jetbrains products comes in a zip file //and icons and shell files are in bin folder of that file) folder
//Icon=/var/local/idea/bin/idea.png  
//The name of icon used by numix circle is "idea.svg"
Icon=idea //this is after the change made by me to work with numix circle.
Exec="/var/local/intellij idea/bin/idea.sh" %f
Comment=Develop with pleasure!
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-idea

2.PhpStorm

//Default Icon path , this is not fixed because it depends the location where user extract and run the PhpStorm folder
//Icon=/var/local/phpstorm/bin/webide.png  
//The name of icon used by numix circle is "phpstorm.svg"
Icon=phpstorm

3.PyCharm

//Default Icon path , this is not fixed because it depends the location where user extract and run the pycharm folder
//Icon=/var/local/pycharm/bin/pycharm.png  
//The name of icon used by numix circle is "pycharm.svg"
Icon=pycharm

4. WebStorm
//Default Icon path , this is not fixed because it depends the location where user extract and run the webstorm folder
//Icon=/var/local/webstorm/bin/webide.png  
//The name of icon used by numix circle is "webide.svg"
Icon=webide

5.RubyMine

//Default Icon path , this is not fixed because it depends the location where user extract and run the rubymine folder
//Icon=/var/local/rubymine/bin/rubymine.png  
//The name of icon used by numix circle is "rubymine.svg"
Icon=rubymine

**Comment by palob** [comment]
In case the icon paths are dependent on where the user chooses to install it isn't possible to universally fix it.

**Comment by Foggalong** [comment]
@palob what's the dealio with [this line](https://github.com/Foggalong/hardcode-fixer/blob/master/tofix.csv#L199)?

**Comment by palob** [comment]
Must have been reported by a Spanish-speaking person who installed it just into their *Downloads* folder. I' wager the fix will be of use to this particular person exclusively :smile:

**Comment by Foggalong** [comment]
Do you know if the `$HOME` variable actually works in that context?

**Comment by palob** [comment]
I don't see why it shouldn't but I'll have a look as to how it plays into the script.

**Comment by Foggalong** [comment]
:+1:

**Comment by palob** [comment]
OK, it doesn't work:

The old icon line plays into the script as string to be changed in the launcher and as location to copy the icon from to ´´.../hicolor/...´´

The only treatment before doing so is ´´current=$(echo "$current" | sed -e "s/\r//g")´´ ([L132](https://github.com/Foggalong/hardcode-fixer/blob/master/fix.sh#L132))

Typing ´´current=$HOME/Descargas/pycharm-community-3.1.1/bin/pycharm.png´´ and ´´current=$(echo "$current" | sed -e "s/\r//g")´´ results in a valid path so there's no problem for the copying.

But since ´´$HOME´´ is evaluated to the actual absolute path grep won't find such string in the launcher file ([line 170](https://github.com/Foggalong/hardcode-fixer/blob/master/fix.sh#L170) for global launchers) and hence nothing can be fixed.

**Comment by palob** [comment]
Could be fixed by using ``/home/${SUDO_USER:-$USER}`` instead of ``$HOME`` like it's done in [lines 18 and 19](https://github.com/Foggalong/hardcode-fixer/blob/master/fix.sh#L18L19) (well, as long as the home directory is located under ``/home``).

**Comment by bil-elmoussaoui** [comment]
The best way to fix those icons; is if the desktop file do exists ask the user to give you the location, you can do that pretty easily, by changing the path in `tofix.csv` with something like `hardcoded-path`. If the desktop file exists, ask the user to give you that location, you can modify the file and change that for future modification ;)

**Comment by Foggalong** [comment]
@bil-elmoussaoui that's a neat idea but I don't think an optimal solution to the problem

@palob I think the script already operates on that assumption so we should be good there

**Comment by bil-elmoussaoui** [comment]
A better idea, 
Just get the `Icon=*` value and replace it in `tofix.csv`

**Comment by Foggalong** [comment]
Unfortunately doesn't work. I can't remember the specifics, but that was how we originally did the fixing but it caused problems with some apps (something with Steam I think).

**Comment by bil-elmoussaoui** [comment]
Even if you don't do it for each application? only for the ones that have `ħardcoded-path` instead of the real path?

**Comment by Foggalong** [comment]
That could work, though if another app in a local location behaves the same way as the previous problematic ones then the same errors will happen

**Comment by bil-elmoussaoui** [comment]
Well, i will try to fix that soon (if possible)

**Comment by bil-elmoussaoui** [comment]
I've a fix of all the hardcoded issues and #145 too but i converted the script to python :/

**Comment by Foggalong** [comment]
I'd like to keep it bash if possible, but happy to give it a look

**Comment by bil-elmoussaoui** [comment]
It will be hard to do with bash :/ What i have ve done now : 
- Add multiple desktop file sources
- Get the hardcoded icon path for hardcoded icons and steam games
- Verify if the icon do exists in the current theme before replacing it in the desktop file
- Create a symlink to the older icon in the "Gnome" theme to fix the issue with the icons don't exists when you change the theme
- Change the icons in `$HOME/.local/share/applications` instead of `usr/share/applications` 
- Install & revert as in the bash script 
Still need to fix some stuffs and i will open a pull request ;)

**Comment by Foggalong** [comment]
I'm not seeing anything there that couldn't be done with bash :P

**Comment by bil-elmoussaoui** [comment]
I'm very bad at bash :( 
Well, that's my script, still need to fix some little stuffs, add a better messages/comments ( i will do if you're okay with that) just run the python script in my fork https://github.com/bil-elmoussaoui/hardcode-fixer
and it's fixes gdebi issue too

**Comment by Foggalong** [comment]
Did you work out what the gdebi issue was? That's the one out of all these that has flumoxed me most.

**Comment by bil-elmoussaoui** [comment]
No idea :/ it's just work

**Comment by leoheck** [comment]
I know bash, maybe I can help with this :)
I just need some time to understand what you are trying to do.

**Comment by leoheck** [comment]
The best idea is to use [this](https://github.com/Foggalong/hardcode-fixer/issues/128#issuecomment-131580943), dosn't make any sense to look for entire path when we want just replace the text. 

We need to find [this issue](https://github.com/Foggalong/hardcode-fixer/issues/128#issuecomment-131581879) because this is making the process complex. Do is possible that this issue was wrong? 

I can think other solutions, but this is the cleanest one. What you think?

**Comment by Foggalong** [comment]
@leoheck wait, so the gdebi issue is working for you now?

**Comment by Foggalong** [comment]
@bil-elmoussaoui I've remembered what the problem with just replacing lines with "Icon=*" was. It meant that every hardcoded icon would be fixed every time, even if the problem had been fixed upstream or previously by the script.

**Comment by bil-elmoussaoui** [comment]
It does not in my case :P As i detect if the return value of `Icon=*` is the same as `fixed_icon` in the csv file

**Comment by Foggalong** [comment]
That still has the problem where if the issue has been fixed upstream (or by a packager) to an icon name different to the one in the CSV then the .desktop file will be needlessly modified :(

**Comment by leoheck** [comment]
1. @Foggalong, the gdebi wasn't numix and I was planning to report it here but after the work with other icons (after many icon cache updates) gdebi becomes numix. I din't understand how it changes. I also purged Numix and resintaled once.

2. @Foggalong, we can update only icons which have extensions. I can create a rexep here after my lunch. But in general we can use the command bellow. I just need test it to guarantte its behavior. I added some expression to handle spaces between ```"="``` as in ```"Icon = file1.png"``` and ```"Icon=file2.svg"```

```bash
sed "s|Icon[\t ]*=[\t ]*.*\..*|Icon=$new|g" file.desktop
```

The ```$current``` name is still required for undo the work.

**Comment by bil-elmoussaoui** [comment]
well gdebi destkop file is not modified at all :/ updating the icon cache wont solve the issue :/

**Comment by leoheck** [comment]
How about to purge then reinstall the numix-circle again.

**Comment by leoheck** [comment]
Reinstalling doesn't work also. 

I think I found the mistake, actually the original icon is: __gnome-mime-application-x-deb__
```
grep Icon /usr/share/applications/gdebi.desktop
Icon=gnome-mime-application-x-deb
```

And the Numix-Circle icon is: __gdebi.svg__

**Comment by bil-elmoussaoui** [comment]
Well, as i said before gdebi uses a mimetype icon instead of an application icon, that's why Numix does not have a symlink from `gdebi` to `gnome-mime-application-x-deb`. The hardcoder fixer should modify the desktop file, change the icon line from `gnome-mime-application-x-deb` to `gdebi` so the correct icon will show up instead of the mimetype icon! And that's not working, updating the icon theme cache won't change anything as the icon name has not been modified by the hardcoder-fixer!

**Comment by leoheck** [comment]
Actually symlink works for me.You need to update the icon cache after make the symlink

```bash
cd /usr/share/icons/Numix-Circle/48x48/apps
ln -s gdebi.svg gnome-mime-application-x-deb.svg
sudo update-icon-caches /usr/share/icons/Numix-Circle
```

**Comment by bil-elmoussaoui** [comment]
A mimetype icon shouldn't be symlinked to an application icon, that's why we use hardcode-fixer :(

**Comment by leoheck** [comment]
Ok, I understand! I know nothing about the guidelines. So, why not to change the icon name with hardcode-fixer?

**Comment by Foggalong** [comment]
That's exactly what we're trying to do but it isn't working -_-'

**Comment by bil-elmoussaoui** [comment]
@rahul8290238014 you're the one who created those desktop file or they're created automatically ?

**Comment by rahul8290238014** [comment]
the desktop files are created automatically and the icon path are set automatically . I edited the desktop file to work with numix icon . They are working properly after changing icon . But if i change the icon from numix to other then icon looks like white files( only if the icon set doesn't have icon for jetbrains ide) on unity launcher. It means one should reset the icon path to the old path so that they could change to their original icon.

**Comment by rahul8290238014** [comment]
all jetbrains ide comes with a .sh file , after execution that launches the ide and creates shortcuts .

**Comment by Foggalong** [comment]
This is now fixed in the latest version thanks to @bil-elmoussaoui :D
