### ISSUE TITLE
Gnu Emacs 24 icon

### ISSUE THREAD

**Issue by erikdubois** [Foggalong/hardcode-fixer#132]
[Desktop Entry]
Version=1.0
Name=GNU Emacs 24
Exec=/usr/bin/emacs24 %F
TryExec=emacs24
Icon=/usr/share/icons/hicolor/scalable/apps/emacs24.svg
Type=Application

in emacs24.desktop

point it to 
Icon=emacs

**Comment by palob** [comment]
Already included in [totfix.csv](https://github.com/Foggalong/hardcode-fixer/blob/master/tofix.csv).

Doesn't work nontheless?

**Comment by erikdubois** [comment]
retested it
works just fine
close
