### ISSUE TITLE
Pypar2.desktop

### ISSUE THREAD

**Issue by erikdubois** [Foggalong/hardcode-fixer#134]
[Desktop Entry]
Name=PyPar2
Comment=A graphical frontend for the par2 utility
Encoding=UTF-8
Exec=pypar2
MimeType=application/x-executable
Terminal=false
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Application
Icon=pypar2.png

Comment[de]=Eine grafische Oberfläche für par2
Comment[fr]=Une interface graphique pour le programme par2
Comment[pl]=Graficzna nakładka na narzędzie par2

Just delete the .png at the end

**Comment by palob** [comment]
Is the name of the file exactly ``Pypar2.desktop``? with upper case **P** at the beginning?

**Comment by erikdubois** [comment]
NO pypar2.desktop  small case
