### ISSUE TITLE
GDebi Package Installer is in csv but not applied

### ISSUE THREAD

**Issue by erikdubois** [Foggalong/hardcode-fixer#140]
Although gdebi is in the csv it is not applied

Filename : gdebi.desktop

content of file

[Desktop Entry]
Name=GDebi Package Installer
GenericName=Package Installer
Comment=Install and view software packages
Exec=gdebi-gtk %f
Icon=gnome-mime-application-x-deb
Terminal=false
Type=Application
Categories=System;
MimeType=application/x-deb;application/x-debian-package;
NotShowIn=KDE;
X-Ubuntu-Gettext-Domain=gdebi
StartupNotify=true
Keywords=package;apt;dpkg;install

Working on linux mint 17.2 clean install

**Comment by fii34** [comment]
Icon=gnome-mime-application-x-deb

There often are two icons. She is in apps, other in mimetypes.
View icon in mimetypes.

**Comment by leoheck** [comment]
The icon should be ```Icon=gdebi```
