### ISSUE TITLE
New icon .desktop location

### ISSUE THREAD

**Issue by leoheck** [Foggalong/hardcode-fixer#145]
Some .desktop files are in ```/usr/local/share/applications``` instead of the default ```/usr/share/applications```

**Comment by palob** [comment]
What do you mean by *custom*?

**Comment by leoheck** [comment]
Updated.

**Comment by palob** [comment]
What's your distro?

**Comment by leoheck** [comment]
Ubuntu 14.04.

 ```
/usr/local/share/applications » ls
AdobeReader.desktop           mimeinfo.cache                NoMachine-status.desktop
arduino.desktop               NoMachine-base.desktop        NoMachine-status-unity.desktop
calibre-ebook-edit.desktop    NoMachine-base-unity.desktop  NoMachine-status-xfce.desktop
calibre-ebook-viewer.desktop  NoMachine-base-xfce.desktop   rfb-receitanet-ajuda.desktop
calibre-gui.desktop           NoMachine-nxs.desktop         rfb-receitanet.desktop
calibre-lrfviewer.desktop     NoMachine-nxv.desktop
 ```

**Comment by Foggalong** [comment]
How odd. That throws a bit of a spanner into how we do scanning but looks like something we do need to address

**Comment by leoheck** [comment]
Yes, actually, it easy to solve, you can change the variable pointing to a single path to a list of paths, then iterate over that list replacing the icons. I can try to make a pull request if you wish.

**Comment by Foggalong** [comment]
@leoheck sure, if you're up for it!

**Comment by leoheck** [comment]
I will make a pull request tonight

**Comment by Foggalong** [comment]
There's also `/usr/share/applications/kde4` which I'd not thought about before. I guess that also means there's `~/.local/share/applications/kde4` and `/usr/local/share/applications/kde4`. Maybe switching to general lists would be a better solution all around?

**Comment by leoheck** [comment]
The fix.sh has the lines above. The ```old_icon``` is overridden in the second line.

```
old_icon="${current//\\/\\\\}" # escape backslashes
old_icon="${old_icon//\//\\/}" # escape slashes
```

At the end of the second line the $old_icon has a ```\``` in front of. This is right? Look at the example:

```
	    Name: 2048-Qt
	Launcher: 2048-qt.desktop
	 Current: /usr/share/pixmaps/2048-qt.xpm
	     New: 2048-qt
	Old icon: __\/usr\/share\/pixmaps\/2048-qt.xpm__
```

**Comment by leoheck** [comment]
I added a flag to disable the execution to ease the tests. I also added a flag to enable verbosity. I changed the ```global_apps``` variable to be ``` global_apps_list``` now and the old ```global_apps``` is now a single path inside a for iteration. I also append the standard output to a file to easy the debug. Anything else?

**Comment by leoheck** [comment]
I am creating a flag to find for hardcoded icons in all known locations.
Please, take a look into [my fork](https://github.com/leoheck/hardcode-fixer.git).

Use the flag ```-f``` to find for hardcoded-icons, the command also generates a csv file to integrate it here in tofix.csv. The screen output is bellow:

```
./fix.sh -f

APPLICATION NAME         LAUNCHER                                                            CURRENT ICON
Skype                    /usr/share/applications/skype.desktop                               skype.png                                                        
ICC Profile Installer    /usr/share/applications/gcm-import.desktop                          application-vnd.iccprofile                                       
Microsoft Calendar       /usr/share/applications/calendar.desktop                            calendar-blue-21.svg                                             
Visual Studio Code       /home/lheck/.local/share/applications/visual-studio-code.desktop    /home/lheck/tools/web/visual-studio-code/resources/app/vso.png   
Wine Internet Explorer   /home/lheck/.local/share/applications/wine-extension-jpe.desktop    7596_iexplore.0                                                  
Wine Internet Explorer   /home/lheck/.local/share/applications/wine-extension-png.desktop    7596_iexplore.0                                                  
Application Teste 2      /home/lheck/.local/share/applications/teste.desktop                 /usr/share/icon/cab_view.png                                     
notepad                  /home/lheck/.local/share/applications/wine-extension-txt.desktop    1E64_notepad.0                                                   
winebrowser              /home/lheck/.local/share/applications/wine-extension-xml.desktop    7765_winebrowser.0                                               
notepad                  /home/lheck/.local/share/applications/wine-extension-ini.desktop    1E64_notepad.0                                                   
wordpad                  /home/lheck/.local/share/applications/wine-extension-wri.desktop    2EF4_wordpad.0                                                   
rundll32                 /home/lheck/.local/share/applications/wine-extension-url.desktop    1CD8_rundll32.0                                                  
winebrowser              /home/lheck/.local/share/applications/wine-extension-htm.desktop    7765_winebrowser.0                                               
winhlp32                 /home/lheck/.local/share/applications/wine-extension-hlp.desktop    4137_winhlp32.0                                                  
Wine Internet Explorer   /home/lheck/.local/share/applications/wine-extension-jfif.desktop   7596_iexplore.0                                                  
Application Teste        /home/lheck/.local/share/applications/TESTE.desktop                 /usr/share/icon/cab_view.png                                     
Wine Internet Explorer   /home/lheck/.local/share/applications/wine-extension-gif.desktop    7596_iexplore.0                                                  
hh                       /home/lheck/.local/share/applications/wine-extension-chm.desktop    A35F_hh.0                                                        
wordpad                  /home/lheck/.local/share/applications/wine-extension-rtf.desktop    2EF4_wordpad.0  
```

I am still working and testing, but you can test it too. Bellow commands are safe to run:
```
./fix.sh -d ----- just print and not execute the commands
./fix.sh -f ----- just find the hardcoded icons and do nothing.
```

What you think?

**Comment by fii34** [comment]
clam-networkeditor_1.4.0-3.1_i386.deb  

/usr/share/mimelnk/application

vnd.clam.network.desktop

[Desktop Entry]
Type=MimeType
MimeType=application/vnd.clam.network
Icon=/usr/share/networkeditor/NetworkEditor-icon.svg
Patterns=*.clamnetwork
Comment=CLAM Processing Network
Comment[ca]=Xarxa de processat de CLAM
Comment[es]=Malla de processado de CLAM

??

MimeType,vnd.clam.network,/usr/share/networkeditor/NetworkEditor-icon.svg,NetworkEditor-icon

??

**Comment by bil-elmoussaoui** [comment]
Try removing a file from this "new" icon desktop location or add a new one and see if that will change anything? 
I don't think that ubuntu will change the standard location just like that. And i'm using ubuntu 14.04 and i don't have this folder

**Comment by leoheck** [comment]
Thanks, @fii34, I didn't finish my fork yet and I didn't check if it works in a regular operation, but the flags I create can show the steps performed by the fix.sh. I will continue updating the fork until I think it can be merged with the original.

**Comment by leoheck** [comment]
@fii34, can you test the program again?

**Comment by fii34** [comment]
leoheck - The script works in /usr/share/applications/kde4/

in /usr/share/mimelnk/application - I can not check

in .desktop no Name=

[Desktop Entry]
Type=MimeType
MimeType=application/vnd.clam.network
Icon=/usr/share/networkeditor/NetworkEditor-icon.svg
Patterns=*.clamnetwork
Comment=CLAM Processing Network
Comment[ca]=Xarxa de processat de CLAM
Comment[es]=Malla de processado de CLAM

?

**********,vnd.clam.network,/usr/share/networkeditor/NetworkEditor-icon.svg,NetworkEditor-icon

I do not know how to write it correctly.

**Comment by leoheck** [comment]
I will test all stuff and maybe try to rewrite some code. I din't have much time this week.
Things we need to know to update the icons

- where is the ```.desktop``` file and its name
- the whole ```Icon= line``` inside ```.desktop``` file

You can also try to change the tofix.csv. The syntax is:
```
vnd.clam.network,LAUNCHER,/usr/share/networkeditor/NetworkEditor-icon.svg,NetworkEditor-icon
```

Replace the __LAUNCHER__ with the _file_ name of the ```.desktop``` file
For example, if launcher is "/usr/share/mimelnk/application/___clam___.desktop" you need to replace LAUNCHER by __clam__

**Comment by fii34** [comment]
But everything works a small error

L: Fixing Ubuntu After Install...
sed: -e expression # 1, a symbol 13: unknown modifier `s'



------------------------------------------------------------------------------

in mimelnk Total 4 .desktop

/usr/share/mimelnk/application/x-latexdraw-project.desktop

[Desktop Entry]
Comment=LaTeXDraw Project
Icon=/usr/share/pixmaps/latexdraw32.xpm
Type=MimeType
MimeType=application/x-latexdraw-project;
Patterns=*.ldp;


/usr/share/mimelnk/application/x-text-pgf.desktop

[Desktop Entry]
Comment=PGF/TikZ drawing
Icon=/usr/share/pixmaps/ktikz32.xpm
Type=MimeType
MimeType=text/x-pgf;
Patterns=*.pgf;*.tikz;


/usr/share/mimelnk/application/vnd.clam.network.desktop

[Desktop Entry]
Type=MimeType
MimeType=application/vnd.clam.network
Icon=/usr/share/networkeditor/NetworkEditor-icon.svg
Patterns=*.clamnetwork
Comment=CLAM Processing Network
Comment[ca]=Xarxa de processat de CLAM
Comment[es]=Malla de processado de CLAM


/usr/share/mimelnk/application/x-progress-quest-save.desktop

[Desktop Entry]
Type=MimeType
MimeType=application/x-progress-quest-save;
Icon=mime_application_x-progress-quest-save.svg
Patterns=*.pq;
Comment=Saved Progress Quest Game

**Comment by fii34** [comment]
15 hours to dig deeper, I found a very simple solution!

I copied the entire script and add it up at the bottom of the page.

In the second copy I just changed this line

global_apps="/usr/share/applications/"

like this

global_apps="/usr/share/applications/kde4/"

3 then added up and replaced on the same line

global_apps="/usr/share/applications/data/"

and so on. Everything works great!


Maybe it's unprofessional, but it works here -r for all folders.

It remains only to add special commands /usr/share/mimelnk/application/

**Comment by bil-elmoussaoui** [comment]
@fii34  I pushed a new commit that fixes this issue. Just wait until this is merged ;)

**Comment by leoheck** [comment]
I fixed this in my fork.. I already propose a pull request.

**Comment by fii34** [comment]
leoheck - In the terminal, everything is OK
In fact not work.

-r 

again sed: -e expression # 1, a symbol 19: unknown modifier `s'

etc

**Comment by leoheck** [comment]
Ok, but how is the command you are using? Which flags? I need to know in which line is this problem. There are many ```sed``` commands in script. You need help me to help you.

**Comment by leoheck** [comment]
I commit an update, try it please!

**Comment by fii34** [comment]
I checked your script to another clean machine.
As a result, the terminal has a list of programs. But all .desktop remained unchanged.
I mean the latest version of your script. 

NEW version not worked

The error message I get with the flag -r

http://i.imgur.com/J9CeMCN.png

In any case, I'm using this script - https://yadi.sk/d/fw4aJ_f4gYiXp

I'm more interested in the modification of the script under 

/usr/share/mimelnk/application/

**Comment by leoheck** [comment]
Ok, I am verifying it right now.
But why you use  ``` sudo bash ./fix.sh``` instead of just ```sudo ./fix.sh``` ?

**Comment by fii34** [comment]
sudo bash fix.sh

This is the work of my script fix2.sh - http://i.imgur.com/B4Kfj46.png

**Comment by leoheck** [comment]
@fii34, I think now I fixed all the problems :), check it out!

**Comment by fii34** [comment]
fix.sh by leoheck  work!

I'm more interested in the modification of the script under

/usr/share/mimelnk/application/

**Comment by bil-elmoussaoui** [comment]
@Foggalong This has been fixed in my pull-request too :)

**Comment by Foggalong** [comment]
@bil-elmoussaoui There's still [this bit to go](https://github.com/Foggalong/hardcode-fixer/issues/145#issuecomment-131942761)
