### ISSUE TITLE
Wine related icons

### ISSUE THREAD

**Issue by leoheck** [Foggalong/hardcode-fixer#152]
This icons are hardcoded?

```
APPLICATION NAME         LAUNCHER              CURRENT ICON 
Wine Internet Explorer   wine-extension-jpe    7596_iexplore.0              
Wine Internet Explorer   wine-extension-png    7596_iexplore.0              
notepad                  wine-extension-txt    1E64_notepad.0               
winebrowser              wine-extension-xml    7765_winebrowser.0           
notepad                  wine-extension-ini    1E64_notepad.0               
wordpad                  wine-extension-wri    2EF4_wordpad.0               
rundll32                 wine-extension-url    1CD8_rundll32.0              
winebrowser              wine-extension-htm    7765_winebrowser.0           
winhlp32                 wine-extension-hlp    4137_winhlp32.0              
Wine Internet Explorer   wine-extension-jfif   7596_iexplore.0              
Wine Internet Explorer   wine-extension-gif    7596_iexplore.0              
hh                       wine-extension-chm    A35F_hh.0                    
wordpad                  wine-extension-rtf    2EF4_wordpad.0    
```

**Comment by Foggalong** [comment]
I dont know. The information is ambiguously formated so I'm not sure which is which

**Comment by leoheck** [comment]
:) Sure! Updated at the 1st line

**Comment by bil-elmoussaoui** [comment]
My wine icons are not hardcoded. Those desktop files are in `usr/share/applications/`?

**Comment by Foggalong** [comment]
See the section of the Numix wiki on [unthemed icons](https://github.com/numixproject/numix-wiki/wiki/Unthemed-Icons#invalid-icon-names). Things to check before we can add it:

1. Does renaming an existing icon to `7596_iexplore.0.svg` theme the relevant launcher?

2. Does adding the icon with this name prevent the cache from properly updating?

**Comment by leoheck** [comment]
I saw the unthemed icons section but the icons i did comment do not fill this rule. AND I don't understand this restristion. We can parse these icons in hardcode-fixer too.

**Comment by Foggalong** [comment]
The restriction is one based on the way GTK cache update worked and isn't something we can change on our end.

I'm asking about creating the icon and whether that works ([#1 above](https://github.com/Foggalong/hardcode-fixer/issues/152#issuecomment-133548118)) because it's possible it's not even hardcoded.

**Comment by leoheck** [comment]
It works, I compied a icon from the Numix-Bevel and it works fine.
![wine_notepad](https://cloud.githubusercontent.com/assets/1277920/9424396/9564ede0-48c1-11e5-9093-bc6d55419f35.png)

**Comment by Foggalong** [comment]
In which case these icons aren't hardcoded, they're just weird looking names.

**Comment by Foggalong** [comment]
The other thing to check was do they stop the cache from being updated?

**Comment by Foggalong** [comment]
@leoheck ^

**Comment by leoheck** [comment]
It don't stop the cache from being updated!

**Comment by Foggalong** [comment]
In which case these need reporting to Numix Circle (and any other icon theme you might want) because they're not hardcoded :)
