### ISSUE TITLE
Photoshop CS6 icon not fixed

### ISSUE THREAD

**Issue by ribeiroevandro** [Foggalong/hardcode-fixer#157]
After running sudo command ./fix.sh the same fixed several icons, with the exception of Photoshop CS6 icon.

```
evandro@ribeiro:~/.hardcode-fixer$ sudo ./fix.sh 
G: Fixing HP Printer...
G: Fixing Intel Graphics Installer...
G: Fixing Python (v2.7)...
G: Fixing Python (v3.4)...
G: Fixing Slingscold...
G: Fixing Valentina Studio...
G: Fixing YouTubeDL GUI...
```
![screenshot from 2015-08-24 20 09 02](https://cloud.githubusercontent.com/assets/943553/9454886/fd851504-4a9b-11e5-838a-de621bfdf4b9.png)

**Comment by Foggalong** [comment]
Can you add the .desktop filename and the icon line from the launcher :)

**Comment by ribeiroevandro** [comment]
```
name and location of .desktop file
/usr/share/applications/Photoshop CS6.desktop

Photoshop CS6.desktop content
[Desktop Entry]
Encoding=UTF-8
Name=Photoshop CS6
Comment=PlayOnLinux
Type=Application
Exec=/usr/share/playonlinux/playonlinux --run "Photoshop CS6" %F
Icon=/home/evandro/.PlayOnLinux//icones/full_size/Photoshop CS6
Name[fr_FR]=Photoshop CS6
StartupWMClass=Photoshop.exe
Categories=
```

**Comment by ribeiroevandro** [comment]
After the upgrade, the icon is still unchanged.

**Comment by Foggalong** [comment]
See [this thread](https://github.com/Foggalong/hardcode-fixer/issues/149#issuecomment-134402920). Hopefully @bil-elmoussaoui will take a look at this this weekend :)

**Comment by ribeiroevandro** [comment]
Show, I'll wait ... Thanks man!

**Comment by Foggalong** [comment]
No problem!
