### ISSUE TITLE
Breaks Copy icon in Gnome-Shell

### ISSUE THREAD

**Issue by xHN35RQ** [Foggalong/hardcode-fixer#158]
After running script, Copy icon is updated just fine in Apps, but small icon in Gnome-Shell is broken:

![screenshot from 2015-08-24 16 37 52](https://cloud.githubusercontent.com/assets/9103375/9455287/79cb70ea-4a7e-11e5-84d1-7d0997c4c7f9.png)

Using latest Numix Icon from PPA on Ubuntu 15.04 Gnome 3

**Comment by bil-elmoussaoui** [comment]
@Foggalong I think that's due to removing the icons from scalable/48x48 in revert

**Comment by Foggalong** [comment]
Maybe we shouldn't remove icons from hicolor on revert?

**Comment by Foggalong** [comment]
Oh wait, this is to do with fixing not reverting

**Comment by bil-elmoussaoui** [comment]
@Foggalong I don't think so..

**Comment by Foggalong** [comment]
@xHN35RQ ?

**Comment by xHN35RQ** [comment]
Umm, all I did was run `fix.sh` and now it shows up like that when using TopIcons extension. Normally these icons would appear down in the message panel and it also show up as broken down there.

Interesting note: no matter what Icon scheme I use, small Copy icons remains broken, even with default Adwaita

**Comment by bil-elmoussaoui** [comment]
You had this issue before? are you using Numix Circle?

**Comment by xHN35RQ** [comment]
No, this issue started when I ran this fixer, and yes I'm using Numix Circle.

**Comment by xHN35RQ** [comment]
Revert does not fix icon, it's still broken.

**Comment by bil-elmoussaoui** [comment]
Can you copy the line for Copy in the "tofix.csv"; and also the desktop file content ?

**Comment by xHN35RQ** [comment]
Aha, I'm using the Ubuntu PPA from paolorotolo, and the icons in the PPA are `/usr/share/icons/hicolor/scalable/apps/copy.svg` and `/usr/share/icons/ubuntu-mono-dark/apps/22/copy.svg` while the csv refers to `/usr/share/icons/hicolor/scalable/apps/copyagent.svg`

**Comment by bil-elmoussaoui** [comment]
Is copy a harcoded application? Can you paste the content of the desktop file :)

**Comment by xHN35RQ** [comment]
Oops sorry, here's content of the desktop file `/usr/share/applications/copy.desktop`

```
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Name=Copy
Exec=/opt/copy-client/CopyAgent
Comment=Sync, Protect and Share. Everywhere.
Icon=copy
Categories=GNOME;GTK;Utility;
```

**Comment by bil-elmoussaoui** [comment]
Can you modifiy the desktop file and change the Icon to `Icon=/usr/share/icons/hicolor/scalable/apps/copy.svg` and then, modify the tofix.csv file to this location and run the script again:
Ropen the script and share the content?

**Comment by xHN35RQ** [comment]
I have to re-write the script because it is hard coded to pull the csv from github.

**Comment by bil-elmoussaoui** [comment]
Nop, you just need to disconnect and remove the tofix.csv from /tmp/

**Comment by xHN35RQ** [comment]
Ok, I reinstalled Copy from PPA, and icons are installed as seen here: https://github.com/PaoloRotolo/copy/tree/master/copy-3.2.01.0481/debian/copy/usr/share/icons and also the desktop file is installed from here: https://github.com/PaoloRotolo/copy/blob/master/copy-3.2.01.0481/copy.desktop

I edit tofix.csv to change Line 35 and Line 36 to `/usr/share/icons/hicolor/scalable/apps/copy.svg`

Running the script produces this file of `copy.desktop` 

```
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Name=Copy
Exec=/opt/copy-client/CopyAgent
Comment=Sync, Protect and Share. Everywhere.
Icon=copy
Categories=GNOME;GTK;Utility;
```
I refresh gtk icon cache, and restart gnome-shell, and still Copy icon is broken.

**Comment by xHN35RQ** [comment]
>  [I think that's due to removing the icons from scalable/48x48 in revert](https://github.com/Foggalong/hardcode-fixer/issues/158#issuecomment-134493006)

I did try to revert before reporting this issue, so maybe that's part of the problem.

**Comment by bil-elmoussaoui** [comment]
Just go to ` /usr/share/icons/hicolor/scalable/apps/` and remove any `copy*` icon there; reinstall copy and use the script again

**Comment by xHN35RQ** [comment]
Ok, I followed your directions. Before running the script I changed Line 35 of the CSV to `/usr/share/icons/hicolor/scalable/apps/copy.svg` then I used the script again and it did not change `copy.desktop` as  you can see: 

```
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Name=Copy
Exec=/opt/copy-client/CopyAgent
Comment=Sync, Protect and Share. Everywhere.
Icon=copy
Categories=GNOME;GTK;Utility;
```
And it's still broken in gnome-shell, so the small application indicators are not being found by Gnome shell no matter what Icon theme is used.

**Comment by xHN35RQ** [comment]
I've given up on this, I'll just live with a broken icon. I've put the application indicators back into the message tray so it won't matter that much.

**Comment by bil-elmoussaoui** [comment]
@xHN35RQ The fact that the icon is not the same in the ALT-Tab switcher is due to `StartupWMClass` in the desktop file of the application. try adding this to your desktop file `StartupWMClass=copy` if not just open your system monitor (gnome system monitor if you're using ubuntu) and change the name from "copy" to the processus name. 

I will install copy in Ubuntu gnome and i will try to reproduce this ;)

**Comment by xHN35RQ** [comment]
Thanks for the suggestion! I was able to learn about `StartupWMClass` and tested this out. Copy runs as `CopyAgent` on Ubuntu 15.04 from Paolo Rotolo's PPA, so it needed to be `StartupWMClass=CopyAgent` and this fixed the Alt-Tab switcher icon. Also, renaming `copy.desktop` to `copyagent.desktop` also fixed the Alt-Tab icon, even without adding a `StartupWMClass` to the desktop file.

However, the icons appearing in the Gnome 3 notifications area are still broken, even though the Alt-Tab icons are now fixed. Thanks for your help!!

**Comment by rodobodolfo** [comment]
Hello, I have exactly the same issue as xHN35RQ.  Using latest Numix Icon from PPA on Ubuntu 15.04 Gnome 3.
Applications, taskbar, and alt-tab icons work great. The notification area icon shows 
![](https://cloud.githubusercontent.com/assets/9103375/9455287/79cb70ea-4a7e-11e5-84d1-7d0997c4c7f9.png)

Let me know if I can help in any way.

**Comment by bil-elmoussaoui** [comment]
@xHN35RQ @rodobodolfo can anyone of you give me the ppa you've used to install Copy? :)

**Comment by rodobodolfo** [comment]
@bil-elmoussaoui  its https://github.com/PaoloRotolo/copy 
thanks!!

**Comment by bil-elmoussaoui** [comment]
Are you sure this is not related to https://github.com/PaoloRotolo/copy/issues/6 ?

**Comment by rodobodolfo** [comment]
Sounds, seems like the same issue... Ive unninstalled the ppa version and intstalled the official package, with same results, probably a copy thing...

**Comment by xHN35RQ** [comment]
@rodobodolfo have you ever used this hardcode-fixer script?

**Comment by rodobodolfo** [comment]
@xHN35RQ  yes, but dind't help with copy. Now that I re read your issue, ulike you, it happened to me even *before* running this script.

**Comment by xHN35RQ** [comment]
> it happened to me even before running this script.

Ah, ok, good to know. It happened to me right around the time I ran the script, so I assumed it's linked........ but now I'm not so sure. I think there's some mis-naming of icons in the Copy package, either Paolo or upstream has introduced the bug recently.

**Comment by Foggalong** [comment]
Are we thinking this is a problem with Copy then?

**Comment by rodobodolfo** [comment]
yes, It seems to be a Copy Issue

**Comment by Foggalong** [comment]
Excellent :+1:
