### ISSUE TITLE
Numix Circle icons for Slack and Gitter does not work after the update 

### ISSUE THREAD

**Issue by azat-io** [Foggalong/hardcode-fixer#171]
Could you add it to your harcore-fixer?

**Comment by azat-io** [comment]
Sorry, Telegram works

**Comment by azat-io** [comment]
Here is Slack for Linux:
Debian / Ubuntu 64-bit: https://slack-ssb-updates.global.ssl.fastly.net/linux_releases/slack-1.2.0-amd64.deb
Debian / Ubuntu 32-bit: https://slack-ssb-updates.global.ssl.fastly.net/linux_releases/slack-1.2.0-i386.deb

**Comment by palob** [comment]
Could you please write down the names of the respective ``.desktop`` files and what the line ``Icon=...`` inside says?

**Comment by Foggalong** [comment]
@azat-io ^

**Comment by azat-io** [comment]
[**Gitter:**](http://gitter.im/apps)

After hardcode-fixer:

```
[Desktop Entry]
Name=Gitter
Comment=Where developers come to talk
Exec=/opt/Gitter/linux64/Gitter
Icon=Gitter
Terminal=false
Type=Application
Categories=Utility;
X-Desktop-File-Install-Version=0.22
```
But at the /usr/share/icons/Numix-Circle/48x48/apps/ there is gitter.svg icon.
Icon not works.

[**Slack:**](https://slack-ssb-updates.global.ssl.fastly.net/linux_releases/slack-1.2.0-amd64.deb)

Without any fixers:

```
[Desktop Entry]
Name=Slack
Comment=Slack Desktop
GenericName=Slack Client for Linux
Exec=/usr/share/slack/slack %U
Icon=slack
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Network;InstantMessaging;
MimeType=text/plain;
```

At the /usr/share/icons/Numix-Circle/48x48/apps/ there is also slack.svg icon.
Icon also not works.

**Comment by azat-io** [comment]
@Foggalong So what could it be?

**Comment by bil-elmoussaoui** [comment]
Just please share the desktop files names so i can try to figure out what's not working

**Comment by bil-elmoussaoui** [comment]
@Foggalong Slack is not hardcoded anymore! And Gitter icon is working with the current version of hardcode-fixer ;) this can be closed

**Comment by azat-io** [comment]
All right! After updating Slack everything works.
