### ISSUE TITLE
Layout and Schematics

### ISSUE THREAD

**Issue by leoheck** [Foggalong/hardcode-fixer#185]
Icon update for icons on issue [2620](https://github.com/numixproject/numix-icon-theme-circle/issues/2620) on numix repository.

They are:

```
/usr/local/share/applications/layout.desktop
Icon=layout.png
```

```
/usr/local/share/applications/schematic.desktop
Icon=layout.png
```

**Comment by bil-elmoussaoui** [comment]
Do you want to use the same icon for both apps?

**Comment by leoheck** [comment]
Doesn't manter. You can decide. I only want a better icon there.
