### ISSUE TITLE
SmartGit fix not working

### ISSUE THREAD

**Issue by fedelevin** [Foggalong/hardcode-fixer#189]
I run fix.sh but my SmartGit icon don't change. (Maybe the problem it's mine)

I have the application in /home/user/Aplicaciones/smartgit. 

You need more info?

**Comment by bil-elmoussaoui** [comment]
Can you share the icon name, the desktop file name? :)

**Comment by fedelevin** [comment]
The icon name says "syntevo-smartgit.png"
The desktop file name is "syntevo-smartgit.desktop"
