### ISSUE TITLE
Various Steam games with hard-coded icons

### ISSUE THREAD

**Issue by Plasmodium1** [Foggalong/hardcode-fixer#196]
Hi, I have noticed various Steam games which appear to have hardcoded icons. All of these have icons in the Numix-Circle folder, but they don't seem to be applied.

For example:
Bioshock Infinite - Steam App id 8870
Civilisation V - Steam App id 8930 (this is in the compatibility list, but running the script has not changed it)
Trine 1 - Steam App id 35700

**Comment by Foggalong** [comment]
We need the file name of the `*.desktop` files to add them to the list. Please add that and we'll add them in!

**Comment by Plasmodium1** [comment]
Apologies. All are in the ~./local/share/applications folder.
They are called:
BioShock Infinite (not sure if capitalisation is important)
Trine
Sid Meier's Civilization V

**Comment by Foggalong** [comment]
Linux file systems are case dependent  so yeah capitalisation needed :)

**Comment by Plasmodium1** [comment]
Thanks. I thought so, but I couldn't remember. BioShock Infinite definitely has a capital S in the middle of the file name!

**Comment by Foggalong** [comment]
Just as a check, are those the "Names" of the `*.desktop` files or the actual file names (as seen when running `ls` in a terminal). We need the latter

**Comment by Plasmodium1** [comment]
![image](https://cloud.githubusercontent.com/assets/11717287/11165971/02d5c004-8b19-11e5-8a61-3439b8b8d76d.png)
This is the output of `<ls`> in that folder. The relevant ones are underlined red. I hope this is what you need!

**Comment by Foggalong** [comment]
Thanks, that's exactly what's needed :)
