### ISSUE TITLE
Mint icons

### ISSUE THREAD

**Issue by zummuz** [Foggalong/hardcode-fixer#215]
Hello.
hardcode-fixer no longer fixes at least 3 icons on Linux Mint (they are in the [list](https://github.com/Foggalong/hardcode-fixer/wiki/App-Support)):
* Mint Drivers 
`Icon=mintdrivers` 
(/usr/share/pixmaps/mintdrivers.svg)
![screenshot from 2015-12-31 21 55 32](https://cloud.githubusercontent.com/assets/13698274/12067458/321616ae-b00b-11e5-8427-6120eeb4fc07.png)

* Mint Software Manager
`Icon=mintinstall`
(/usr/share/pixmaps/mintinstall.svg)
![screenshot from 2015-12-31 22 02 41](https://cloud.githubusercontent.com/assets/13698274/12067465/3960e718-b00b-11e5-99ec-c4fb234fb93f.png)

* Mint Software Sources
`Icon=mintsources`
(/usr/share/pixmaps/mintsources.svg)
![screenshot from 2015-12-31 22 06 00](https://cloud.githubusercontent.com/assets/13698274/12067468/3ddbb002-b00b-11e5-8932-fbcb78da1f18.png)

**Comment by bil-elmoussaoui** [comment]
We need the desktop file name too :)

**Comment by zummuz** [comment]
Im not sure what do you ask. This:
mintdrivers.desktop
`Name=Driver Manager`

mintinstall.desktop
`Name=Software Manager`

mintsources.desktop
`Name=Software Sources`
?

**Comment by bil-elmoussaoui** [comment]
Yes, thanks;

**Comment by zummuz** [comment]
It should already work?
I guess I've reported something wrong, because it isn't.

**Comment by bil-elmoussaoui** [comment]
Yes but you will need to execute the script again

**Comment by bil-elmoussaoui** [comment]
Try to logout and log in

**Comment by zummuz** [comment]
I've executed teh script again and relogged - doesn't work

**Comment by bil-elmoussaoui** [comment]
What was the output when you've executed the script? Can i get the content of each desktop file too?

**Comment by bil-elmoussaoui** [comment]
You have used `sudo ./fix.sh`?

**Comment by zummuz** [comment]
It was silent, then I deleted all with `-r` and executed again:
`G: Fixing GDebi...`
`G: Fixing HP Printer...`
`G: Fixing Mint Backup...`
`G: Fixing Mint Backup...`
`G: Fixing Mint Nanny...`
`G: Fixing Mint Upload Manager...`
`G: Fixing Nvidia Settings...`
`G: Fixing Python (v2.7)...`
`G: Fixing Python (v3.4)...`
>You have used sudo ./fix.sh?

Yes
>Can i get the content of each desktop file too?

I've deleted Name[%lang]= and Comment[%lang]= lines.
* mintdrivers.desktop:
[Desktop Entry]
Name=Driver Manager
Exec=driver-manager
Icon=mintdrivers
Terminal=false
X-MultipleArgs=false
Type=Application
Categories=GNOME;GTK;System;Settings;X-GNOME-SystemSettings;X-GNOME-Settings-Panel;XFCE;X-XFCE-SettingsDialog;X-XFCE-SystemSettings;
X-GNOME-Settings-Panel=driver-manager
X-KDE-SubstituteUID=true
NotShowIn=KDE;

* mintdrivers.desktop:
[Desktop Entry]
Name=Software Manager
Exec=gksu mintinstall
Icon=mintinstall
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;System;Settings;XFCE;X-XFCE-SettingsDialog;X-XFCE-SystemSettings;
NotShowIn=KDE;

* mintsources.desktop:
[Desktop Entry]
Name=Software Sources
Exec=software-sources
Icon=mintsources
Terminal=false
X-MultipleArgs=false
Type=Application
Categories=GNOME;GTK;System;Settings;X-GNOME-SystemSettings;X-GNOME-Settings-Panel;XFCE;X-XFCE-SettingsDialog;X-XFCE-SystemSettings;
X-GNOME-Settings-Panel=software-properties
MimeType=text/x-apt-sources-list;
X-KDE-SubstituteUID=true
NotShowIn=KDE;

**Comment by bil-elmoussaoui** [comment]
can you share the output of `tree /usr/share/applications/`?

**Comment by bil-elmoussaoui** [comment]
The icons seem to not be hardcoded at all...Are you using Numix Circle? If so , try updating icon cache. `sudo gtk-update-icon-cache -f /usr/share/icons/Numix-Circle/`

**Comment by zummuz** [comment]
/usr/share/applications/
├── apturl_mime.desktop
├── audacious.desktop
├── audacity.desktop
├── banshee-audiocd.desktop
├── banshee.desktop
├── banshee-media-player.desktop
├── baobab.desktop
├── bluetooth-sendto.desktop
├── bluetooth-wizard.desktop
├── brasero.desktop
├── brasero-nautilus.desktop
├── chromium-browser.desktop
├── cinnamon2d.desktop
├── cinnamon-bluetooth-properties.desktop
├── cinnamon-color-panel.desktop
├── cinnamon-control-center.desktop
├── cinnamon-datetime-panel.desktop
├── cinnamon.desktop
├── cinnamon-display-panel.desktop
├── cinnamon-killer-daemon.desktop
├── cinnamon-menu-editor.desktop
├── cinnamon-network-panel.desktop
├── cinnamon-region-panel.desktop
├── cinnamon-screensaver.desktop
├── cinnamon-settings-applets.desktop
├── cinnamon-settings-backgrounds.desktop
├── cinnamon-settings-calendar.desktop
├── cinnamon-settings-daemon.desktop
├── cinnamon-settings-default.desktop
├── cinnamon-settings-desklets.desktop
├── cinnamon-settings.desktop
├── cinnamon-settings-desktop.desktop
├── cinnamon-settings-effects.desktop
├── cinnamon-settings-extensions.desktop
├── cinnamon-settings-fonts.desktop
├── cinnamon-settings-general.desktop
├── cinnamon-settings-hotcorner.desktop
├── cinnamon-settings-info.desktop
├── cinnamon-settings-keyboard.desktop
├── cinnamon-settings-mouse.desktop
├── cinnamon-settings-notifications.desktop
├── cinnamon-settings-panel.desktop
├── cinnamon-settings-power.desktop
├── cinnamon-settings-privacy.desktop
├── cinnamon-settings-screensaver.desktop
├── cinnamon-settings-startup.desktop
├── cinnamon-settings-themes.desktop
├── cinnamon-settings-tiling.desktop
├── cinnamon-settings-user.desktop
├── cinnamon-settings-users.desktop
├── cinnamon-settings-windows.desktop
├── cinnamon-settings-workspaces.desktop
├── cinnamon-sound-nua-panel.desktop
├── cinnamon-sound-panel.desktop
├── cinnamon-universal-access-panel.desktop
├── cinnamon-wacom-panel.desktop
├── defaults.list -> /etc/gnome/defaults.list
├── eog.desktop
├── evince.desktop
├── evince-previewer.desktop
├── file-roller.desktop
├── firefox.desktop
├── gcalctool.desktop
├── gcr-prompter.desktop
├── gcr-viewer.desktop
├── gdebi.desktop
├── gedit.desktop
├── gimp.desktop
├── gkbd-keyboard-display.desktop
├── gksu.desktop
├── gnome-disk-image-mounter.desktop
├── gnome-disk-image-writer.desktop
├── gnome-disks.desktop
├── gnome-font-viewer.desktop
├── gnome-panel.desktop
├── gnome-power-statistics.desktop
├── gnome-screenshot.desktop
├── gnome-system-log.desktop
├── gnome-system-monitor.desktop
├── gnome-terminal.desktop
├── gthumb.desktop
├── gthumb-import.desktop
├── gucharmap.desktop
├── gufw.desktop
├── hexchat.desktop
├── hplj1020.desktop
├── icedtea-netx-javaws.desktop
├── im-config.desktop
├── inkscape.desktop
├── itweb-settings.desktop
├── kde4
│   ├── mintBackup.desktop
│   ├── mintdrivers.desktop
│   ├── mintNanny.desktop
│   ├── mintsources.desktop
│   ├── mintupload.desktop
│   └── mintWelcome.desktop
├── libreoffice-base.desktop
├── libreoffice-calc.desktop
├── libreoffice-draw.desktop
├── libreoffice-impress.desktop
├── libreoffice-math.desktop
├── libreoffice-startcenter.desktop
├── libreoffice-writer.desktop
├── libreoffice-xsltfilter.desktop -> /usr/lib/libreoffice/share/xdg/xsltfilter.desktop
├── lynis.desktop
├── metacity.desktop
├── mimeinfo.cache
├── mintBackup.desktop
├── mintBackup_mime.desktop
├── mintdrivers.desktop
├── mintinstall.desktop
├── mintinstall-kde.desktop
├── mintinstall-mime.desktop
├── mintLocale.desktop
├── mintlocale-im.desktop
├── mintNanny.desktop
├── mintsources.desktop
├── mintstick.desktop
├── mintstick-format.desktop
├── mintstick-format-kde.desktop
├── mintstick-kde.desktop
├── mintupdate.desktop
├── mintupdate-kde.desktop
├── mintupload.desktop
├── mint-user-guide.desktop
├── mintWelcome.desktop
├── mono-runtime-common.desktop
├── mono-runtime-terminal.desktop
├── nemo-autorun-software.desktop
├── nemo-autostart.desktop
├── nemo.desktop
├── nm-applet.desktop
├── nm-applet_mate.desktop
├── nm-connection-editor.desktop
├── notification-daemon.desktop
├── nvidia-settings.desktop
├── openjdk-7-java.desktop
├── openjdk-7-policytool.desktop
├── orca.desktop
├── pidgin.desktop
├── python2.7.desktop
├── python3.4.desktop
├── screensavers
│   ├── abstractile.desktop
│   ├── anemone.desktop
│   ├── anemotaxis.desktop
│   ├── antinspect.desktop
│   ├── antmaze.desktop
│   ├── antspotlight.desktop
│   ├── apollonian.desktop
│   ├── apple2.desktop
│   ├── atlantis.desktop
│   ├── attraction.desktop
│   ├── atunnel.desktop
│   ├── barcode.desktop
│   ├── blaster.desktop
│   ├── blinkbox.desktop
│   ├── blitspin.desktop
│   ├── blocktube.desktop
│   ├── boing.desktop
│   ├── bouboule.desktop
│   ├── bouncingcow.desktop
│   ├── boxed.desktop
│   ├── boxfit.desktop
│   ├── braid.desktop
│   ├── bubble3d.desktop
│   ├── bumps.desktop
│   ├── cage.desktop
│   ├── carousel.desktop
│   ├── ccurve.desktop
│   ├── celtic.desktop
│   ├── circuit.desktop
│   ├── cloudlife.desktop
│   ├── companioncube.desktop
│   ├── compass.desktop
│   ├── coral.desktop
│   ├── crackberg.desktop
│   ├── crystal.desktop
│   ├── cube21.desktop
│   ├── cubenetic.desktop
│   ├── cubestorm.desktop
│   ├── cubicgrid.desktop
│   ├── cwaves.desktop
│   ├── cynosure.desktop
│   ├── dangerball.desktop
│   ├── decayscreen.desktop
│   ├── deco.desktop
│   ├── deluxe.desktop
│   ├── demon.desktop
│   ├── discrete.desktop
│   ├── distort.desktop
│   ├── drift.desktop
│   ├── endgame.desktop
│   ├── engine.desktop
│   ├── epicycle.desktop
│   ├── eruption.desktop
│   ├── euler2d.desktop
│   ├── extrusion.desktop
│   ├── fadeplot.desktop
│   ├── fiberlamp.desktop
│   ├── fireworkx.desktop
│   ├── flame.desktop
│   ├── flipflop.desktop
│   ├── flipscreen3d.desktop
│   ├── fliptext.desktop
│   ├── flow.desktop
│   ├── fluidballs.desktop
│   ├── flurry.desktop
│   ├── flyingtoasters.desktop
│   ├── fontglide.desktop
│   ├── fuzzyflakes.desktop
│   ├── galaxy.desktop
│   ├── gears.desktop
│   ├── gflux.desktop
│   ├── glblur.desktop
│   ├── glcells.desktop
│   ├── gleidescope.desktop
│   ├── glhanoi.desktop
│   ├── glknots.desktop
│   ├── glmatrix.desktop
│   ├── glplanet.desktop
│   ├── glschool.desktop
│   ├── glslideshow.desktop
│   ├── glsnake.desktop
│   ├── gltext.desktop
│   ├── goop.desktop
│   ├── grav.desktop
│   ├── greynetic.desktop
│   ├── halftone.desktop
│   ├── halo.desktop
│   ├── helix.desktop
│   ├── hilbert.desktop
│   ├── hopalong.desktop
│   ├── hypertorus.desktop
│   ├── hypnowheel.desktop
│   ├── ifs.desktop
│   ├── imsmap.desktop
│   ├── interaggregate.desktop
│   ├── interference.desktop
│   ├── intermomentary.desktop
│   ├── jigglypuff.desktop
│   ├── jigsaw.desktop
│   ├── juggler3d.desktop
│   ├── julia.desktop
│   ├── kaleidescope.desktop
│   ├── klein.desktop
│   ├── kumppa.desktop
│   ├── lament.desktop
│   ├── lavalite.desktop
│   ├── lcdscrub.desktop
│   ├── lockward.desktop
│   ├── loop.desktop
│   ├── m6502.desktop
│   ├── maze.desktop
│   ├── memscroller.desktop
│   ├── menger.desktop
│   ├── metaballs.desktop
│   ├── mirrorblob.desktop
│   ├── moebius.desktop
│   ├── moebiusgears.desktop
│   ├── moire2.desktop
│   ├── moire.desktop
│   ├── molecule.desktop
│   ├── morph3d.desktop
│   ├── mountain.desktop
│   ├── munch.desktop
│   ├── nerverot.desktop
│   ├── noof.desktop
│   ├── noseguy.desktop
│   ├── pacman.desktop
│   ├── pedal.desktop
│   ├── penetrate.desktop
│   ├── penrose.desktop
│   ├── petri.desktop
│   ├── phosphor.desktop
│   ├── photopile.desktop
│   ├── piecewise.desktop
│   ├── pinion.desktop
│   ├── pipes.desktop
│   ├── polyhedra.desktop
│   ├── polyominoes.desktop
│   ├── polytopes.desktop
│   ├── pong.desktop
│   ├── providence.desktop
│   ├── pulsar.desktop
│   ├── pyro.desktop
│   ├── qix.desktop
│   ├── queens.desktop
│   ├── rd-bomb.desktop
│   ├── ripples.desktop
│   ├── rocks.desktop
│   ├── rorschach.desktop
│   ├── rotzoomer.desktop
│   ├── rubikblocks.desktop
│   ├── rubik.desktop
│   ├── sballs.desktop
│   ├── shadebobs.desktop
│   ├── sierpinski3d.desktop
│   ├── sierpinski.desktop
│   ├── skytentacles.desktop
│   ├── slidescreen.desktop
│   ├── slip.desktop
│   ├── sonar.desktop
│   ├── speedmine.desktop
│   ├── spheremonics.desktop
│   ├── spotlight.desktop
│   ├── sproingies.desktop
│   ├── squiral.desktop
│   ├── stairs.desktop
│   ├── starfish.desktop
│   ├── starwars.desktop
│   ├── stonerview.desktop
│   ├── strange.desktop
│   ├── substrate.desktop
│   ├── superquadrics.desktop
│   ├── surfaces.desktop
│   ├── swirl.desktop
│   ├── tangram.desktop
│   ├── thornbird.desktop
│   ├── timetunnel.desktop
│   ├── topblock.desktop
│   ├── triangle.desktop
│   ├── tronbit.desktop
│   ├── truchet.desktop
│   ├── twang.desktop
│   ├── vermiculate.desktop
│   ├── vidwhacker.desktop
│   ├── voronoi.desktop
│   ├── wander.desktop
│   ├── whirlwindwarp.desktop
│   ├── wormhole.desktop
│   ├── xanalogtv.desktop
│   ├── xflame.desktop
│   ├── xjack.desktop
│   ├── xlyap.desktop
│   ├── xmatrix.desktop
│   ├── xrayswarm.desktop
│   ├── xspirograph.desktop
│   └── zoom.desktop
├── seahorse.desktop
├── signon-ui-browser-process.desktop
├── simple-scan.desktop
├── smplayer.desktop
├── smplayer_enqueue.desktop
├── synaptic.desktop
├── synaptic-kde.desktop
├── system-config-printer.desktop
├── thunderbird.desktop
├── tomboy.desktop
├── totem.desktop
├── transmission-gtk.desktop
├── vino-preferences.desktop
├── vlc.desktop
├── wireshark.desktop
└── yelp.desktop

2 directories, 354 files

**Comment by zummuz** [comment]
>Are you using Numix Circle?

Yes
>If so , try updating icon cache. sudo gtk-update-icon-cache -f /usr/share/icons/Numix-Circle/

Ok, I just did. What should it do?

**Comment by bil-elmoussaoui** [comment]
Icon themes create a cache file, when you do change something on the theme you need to always refreshing the icon cache. You can find more details by googling that. 

If the icons are still not fixed, i think that we are not modifying the right desktop files..Can you do some searches? Here's a list of where you can find desktop files 
- /usr/share/applications/
- /usr/local/share/applications/
- /usr/local/share/applications/kde4
- ~/.local/share/applications/
- ~/.local/share/applications/kde4

**Comment by zummuz** [comment]
>Icon themes create a cache file, when you do change something on the theme you need to always refreshing the icon cache. You can find more details by googling that.

Yeah, I've googled quickly before asking, and understood this action serves for optimization. I'll google more later.

There are no such folders:
/usr/local/share/applications/
/usr/local/share/applications/
~/.local/share/applications/kde4

and
~/.local/share/applications/
contains one desktop file (serapp-gedit-EPRCAY.desktop)

**Comment by bil-elmoussaoui** [comment]
Can you try an application like Menulibre to edit desktop files and see if you can change those icons?

**Comment by zummuz** [comment]
Yeah, I've successfully changed icon for Software Sources with random picture from ~/Pictures

**Comment by bil-elmoussaoui** [comment]
I'm really out of ideas...Mint was always a pain to fix, i don't know why they don't follow any standards..

**Comment by zummuz** [comment]
Okay, there are two types of icons for Drivers and Sources, icons work in the settings window and don't work in kickoff panel:
![screenshot from 2016-01-01 11 30 10](https://cloud.githubusercontent.com/assets/13698274/12070301/1b7fb7da-b07c-11e5-8a11-f5c8701b2fd8.png)
Then I just copied and renamed /usr/share/icons/Numixfolder/scalable/apps/youtube.svg to /usr/share/icons/Numixfolder/scalable/apps/mintinstall.svg:
![screenshot from 2016-01-01 11 34 49](https://cloud.githubusercontent.com/assets/13698274/12070308/8cd259ba-b07c-11e5-866d-75b672437dea.png)
So I guess there should be added 3 regular (not  hardcoded fixed) icons with names `mintdrivers.svg`, `mintinstall.svg` and `mintsources.svg`.

**Comment by bil-elmoussaoui** [comment]
Well your icons were never hardcoded dude...Just few missing symlinks.. 
@Foggalong Please revert my latest commit..

**Comment by zummuz** [comment]
I was told that they are, and there are similar icons in the list of supported ones.
Anyway, this symlinks will be added/fixed or should I report them to Numix-Circle?

**Comment by bil-elmoussaoui** [comment]
The best thing is to report them to Numix Circle; Well because in older version those icons were hardcoded; i think they are not hardcoded anymore

**Comment by zummuz** [comment]
Okay, thanks
btw, multiple icons should be reported in one issue or in a separate ones?

**Comment by bil-elmoussaoui** [comment]
See this https://github.com/numixproject/numix-icon-theme-circle/pull/2760

**Comment by palob** [comment]
@bil-elmoussaoui Why reverting?

**Comment by bil-elmoussaoui** [comment]
@palob Those were not hardcoded at all..and the hardcoded icon line, is just a normal location for icons like `/usr/share/icons/`

**Comment by palob** [comment]
As far as I can see it was ``usr/share/pixmaps``.
Anyway, any line which does't work with SVG icons in either ``/usr/share/icons/Numix/`` or ``~/.local/share/icons/Numix`` or ``~/.icons/Numix`` is to be considered hardcoded.
The entry won't do any harm.

**Comment by bil-elmoussaoui** [comment]
Icon=mintdrivers  : this the icon line
(/usr/share/pixmaps/mintdrivers.svg) this is the icon location in his desktop
Well, it won't do any harm as you said ;)
