### ISSUE TITLE
Cisco AnyConnect hardcoded icon

### ISSUE THREAD

**Issue by r0ckarong** [Foggalong/hardcode-fixer#224]
Cisco AnyConnect VPN uses a hardcoded icon:

This is `/usr/share/applications/cisco-anyconnect.desktop`

[Desktop Entry]
Type=Application
Name=Cisco Anyconnect Secure Mobility Client
Comment=Connect to a private network using the Cisco Anyconnect Secure Mobility Client
Exec=/opt/cisco/anyconnect/bin/vpnui
Icon=/opt/cisco/anyconnect/pixmaps/vpnui48.png
Terminal=false
Encoding=UTF-8

The icon name is vpnui48.png

I have uploaded an icon design to remedy this here: https://github.com/numixproject/numix-icon-theme-circle/pull/2854

**Comment by Foggalong** [comment]
Do you have the file name of the .desktop file?

**Comment by mnapp** [comment]
Just updated the original comment with it. Realized this too late.
