### ISSUE TITLE
Slack 2.0.3+ hardcoded icon

### ISSUE THREAD

**Issue by vysinsky** [Foggalong/hardcode-fixer#227]
Hi, the latest Slack version (currently 2.0.3) uses hardcoded icon.

Desktop entry `/usr/share/applications/slack.desktop`:

```
[Desktop Entry]
Name=Slack
Comment=Slack Desktop
GenericName=Slack Client for Linux
Exec=/usr/bin/slack --disable-gpu %U
Icon=/usr/share/pixmaps/slack.png
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Network;InstantMessaging;
MimeType=x-scheme-handler/slack;
```

Slack icon is available in Numix-Circle and changing to `Icon=slack` works (as long as there is no update).

**Comment by palob** [comment]
If you wish your customised launchers to survive updates just copy them over to ``~/.local/share/applications``

**Comment by vysinsky** [comment]
Wow. Cool. Thank you! :)

**Comment by erikdubois** [comment]
Hi, not sure if this is still open but I am on solus budgie/mate 1.2.1
and running the script does not fix the icon
same text as above to be sure I will copy it from my system

/usr/share/applications/slack.desktop

[Desktop Entry]
Name=Slack
Comment=Slack Desktop
GenericName=Slack Client for Linux
Exec=/usr/bin/slack --disable-gpu %U
Icon=/usr/share/pixmaps/slack.png
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Network;InstantMessaging;
MimeType=x-scheme-handler/slack;

It seems the same code.
Like I said not sure if it is solved or not.

**Comment by erikdubois** [comment]
now I installed it on linux mint
same issue

[Desktop Entry]
Name=Slack
Comment=Slack Desktop
GenericName=Slack Client for Linux
Exec=/usr/bin/slack --disable-gpu %U
Icon=/usr/share/pixmaps/slack.png
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Network;InstantMessaging;
MimeType=x-scheme-handler/slack;

**Comment by bil-elmoussaoui** [comment]
@Foggalong fixed
