### ISSUE TITLE
Jetbrains products not being fixed

### ISSUE THREAD

**Issue by Tcenova** [Foggalong/hardcode-fixer#229]
Pycharm Professional, Intellij IDEA, Clion, and Android Studio are all not being fixed by this script. they are all the newest versions installed through umake on ubuntu 14.04.

Here is the output from running the script ran with sudo:

Desktop$ sudo ./fix.sh
G: Fixing Emacs 23...
G: Fixing HP Printer...
G: Fixing IDLE 3...
G: Fixing IDLE (Python 3.4)...
G: Fixing Image Magick...
G: Fixing Nvidia Settings...
G: Fixing Python (v2.7)...
G: Fixing Python (v3.4)...
G: Fixing Skype...
G: Fixing SuperTuxKart...
G: Fixing Ubuntu Web Browser...
G: Fixing X-Diagnose...

Here are the .desktop locations and contents:
all are in /home/thomas/.local/share/applications

jetbains-idea.desktop

[Desktop Entry]
Version=1.0
Type=Application
Name=IntelliJ IDEA
Icon=/home/thomas/.local/share/umake/ide/idea-ultimate/bin/idea.png
Exec="/home/thomas/.local/share/umake/ide/idea-ultimate/bin/idea.sh" %f
Comment=IntelliJ IDEA (UDTC)
Categories=Development;IDE;
Terminal=false

jetbrains-pycharm.desktop

[Desktop Entry]
Version=1.0
Type=Application
Name=PyCharm Professional Edition
Icon=/home/thomas/.local/share/umake/ide/pycharm-professional/bin/pycharm.png
Exec="/home/thomas/.local/share/umake/ide/pycharm-professional/bin/pycharm.sh" %f
Comment=PyCharm Professional Edition (UDTC)
Categories=Development;IDE;
Terminal=false

jetbrains-clion.desktop

[Desktop Entry]
Version=1.0
Type=Application
Name=CLion integrated C/C++ IDE
Icon=/home/thomas/.local/share/umake/ide/clion/bin/clion.svg
Exec="/home/thomas/.local/share/umake/ide/clion/bin/clion.sh" %f
Comment=CLion integrated C/C++ IDE (UDTC)
Categories=Development;IDE;
Terminal=false

android-studio.desktop

[Desktop Entry]
Version=1.0
Type=Application
Name=Android Studio
Icon=/home/thomas/.local/share/umake/android/android-studio/bin/studio.png
Exec="/home/thomas/.local/share/umake/android/android-studio/bin/studio.sh" %f
Comment=Android Studio developer environment
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-android-studio

Hope this helps solve the issue.

**Comment by bil-elmoussaoui** [comment]
The Jetbrains products are using a hardcoded icon path, this should be fixed in my PR #213 
Can you give it a try? :+1:

**Comment by Tcenova** [comment]
Sure! It worked for Pycharm and Intellij IDEA but not Clion or Android Studio.

**Comment by bil-elmoussaoui** [comment]
Well, the Clion and Android studio are missing from the tofix.csv file! i will open a PR to fix that
