### ISSUE TITLE
Question on Hardcoded Icon Fixer

### ISSUE THREAD

**Issue by ElvisPresly** [Foggalong/hardcode-fixer#232]
Hardcoded Icon Fixer is already included in Numix-circle repository? Whether it is necessary to add him to automatic loading what it would be started also by etc? Or after the Numix-circle installation it isn't necessary to do anything else, and Hardcoded Icon Fixer works automatically?

**Comment by palob** [comment]
To your last question: No, you need to run it manually.

**Comment by ElvisPresly** [comment]
He needs to be added to automatic loading? Or 1 time is enough to start of it, and then to wait for the new version?
