### ISSUE TITLE
Enpass not fix

### ISSUE THREAD

**Issue by ElvisPresly** [Foggalong/hardcode-fixer#234]
Application of Enpass is fixed. But after reset again an old icon.
![2016-04-19 22 35 41](https://cloud.githubusercontent.com/assets/18265958/14652930/404c4dc2-067f-11e6-90a6-dfc5d0b1598a.png)

**Comment by bil-elmoussaoui** [comment]
It's an other issue,  please report it here https://github.com/bil-elmoussaoui/StartupWMClassFixer
Enpass does not use a hardcoded icon path
