### ISSUE TITLE
Viber fix not working

### ISSUE THREAD

**Issue by JefersonFG** [Foggalong/hardcode-fixer#235]
I just found about the script today, tried it but it didn't change Viber's icon. If it helps, Viber was updated today to version 6.0.1, so maybe the new version changed the icon place. Can you take a look?

![captura de tela de 2016-04-24 22-11-29](https://cloud.githubusercontent.com/assets/11379617/14771698/844fbbb0-0a69-11e6-8ddd-1315f8594e70.png)

**Comment by JefersonFG** [comment]
After rebooting the computer the problem was corrected. Is it intended? If so, add in the description of the script ;)

**Comment by Foggalong** [comment]
It should work without the reboot. When you were running the script did the icon cache update correctly?

**Comment by JefersonFG** [comment]
Yes, it did show the expected output. I even tried removing and reapplying the theme but it didn't work, that's why I started the issue. But after the reboot everything is working as intended.

**Comment by Foggalong** [comment]
That's very bizarre. Did this happen with any other programs?

**Comment by JefersonFG** [comment]
I didn't note anything else happening. The script "corrected" other programs that were showing themed icons (like Skype and Telegram), but nothing changed.

I'm running Fedora 23 64-bits (the standard GNOME version) and the Viber version is 6.0.1

**Comment by Foggalong** [comment]
Thanks :+1:

**Comment by bil-elmoussaoui** [comment]
Can you share the content of the desktop file?

**Comment by bil-elmoussaoui** [comment]
Ping?

**Comment by JefersonFG** [comment]
Sorry for not answering before, I don't have the same desktop anymore, sorry.
