### ISSUE TITLE
Linux Mint 18 /usr/share/applications/mintbackup_mime.desktop

### ISSUE THREAD

**Issue by erikdubois** [Foggalong/hardcode-fixer#238]
[Desktop Entry]
Name=Backup Tool
Exec=mintBackup
Icon=/usr/share/pixmaps/mintbackup/icon.png

change to 

Icon=mintbackup

**Comment by erikdubois** [comment]
Not yet fixed - tested it on Linux Mint 18 stable
the icon resides now in pixmaps.

Icon=/usr/share/pixmaps/mintbackup/icon.svg

in the tofix.csv I see another path

/usr/lib/linuxmint/mintBackup/icon.png

**Comment by Foggalong** [comment]
Ooops, my bad! Fixed now :)
