### ISSUE TITLE
mintbackup.desktop in /usr/share/applications

### ISSUE THREAD

**Issue by erikdubois** [Foggalong/hardcode-fixer#242]
Changes are for the latest stable version of Linux Mint Mate 18

Exec=mintbackup
Icon=/usr/share/pixmaps/mintbackup/icon.svg
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;System;Settings
NotShowIn=KDE;

change to 

mintbackup

**Comment by erikdubois** [comment]
i just made an error in my own script to change these two backup items
this one  has an svg extension
the other mintbackup is a png

**Comment by Foggalong** [comment]
Now £8.
