### ISSUE TITLE
mintbackup_mime.desktop in /usr/share/applications

### ISSUE THREAD

**Issue by erikdubois** [Foggalong/hardcode-fixer#243]
For the latest stable version of linux mint 18 mate

Exec=mintBackup
Icon=/usr/share/pixmaps/mintbackup/icon.png
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;System;Settings
NoDisplay=true
MimeType=application/x-backup;

change to 

mintbackup

**Comment by Foggalong** [comment]
If I had £1 for every time Mint have messed with this desktop file I'd have £7 now.
