### ISSUE TITLE
Add Sabnzbd

### ISSUE THREAD

**Issue by Paviluf** [Foggalong/hardcode-fixer#249]
Hello,

Sabnzbd have a hardcoded icon `Icon=/usr/share/SABnzbd/icons/nzb.ico`

I have also opened an issue against Sabnzbd to avoid using a hardcoded icon https://github.com/sabnzbd/sabnzbd/issues/659

Thanks !

**Comment by Paviluf** [comment]
The Sabnzbd dev think it's not really feasible to have a standard icon https://github.com/sabnzbd/sabnzbd/issues/659 If someone have an idea to fix it it will be great if he can talk to him on the Sabnzbd issue

https://github.com/sabnzbd/sabnzbd/issues/659

**Comment by Foggalong** [comment]
As far as I know, free desktop standards don't require the inclusion of a launcher (though I could be wrong on that). Instead you should be appealing to the packagers of whatever distribution you're using to fix this there.

**Comment by Paviluf** [comment]
Ok thanks.

**Comment by Paviluf** [comment]
Thank you !
