### ISSUE TITLE
Franz

### ISSUE THREAD

**Issue by erikdubois** [Foggalong/hardcode-fixer#258]
Reported it on github
https://gist.github.com/jamiesoncj/756728b3ba7c07d7a90f843400af37bb
/usr/share/applications/franz.desktop

[Desktop Entry]
Name=Franz
Comment=
Exec=/opt/franz/Franz
Icon=/opt/franz/franz-icon.png
Terminal=false
Type=Application
Categories=Messaging,Internet

to 

Icon=franz

thanks

**Comment by erikdubois** [comment]
Franz has been doublechecked.
OK

**Comment by mikmik** [comment]
Hi Erik,
On Ubuntu 17.04 there are folders in /hicolor... and placing the icon there does not work.
I'm searching for the correct way to do it.
