### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by erikdubois** [Foggalong/hardcode-fixer#259]
/usr/share/applications/telegram.desktop

[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Name=Telegram
Exec=/opt/telegram/Telegram %u
Comment=Network taking back our right to privacy.
Icon=/opt/telegram/telegram.svg
Categories=GNOME;GTK;Network;
MimeType=application/x-xdg-protocol-tg;x-scheme-handler/tg;

to
Icon=telegram

**Comment by bil-elmoussaoui** [comment]
@Foggalong  This is already included in the database file

**Comment by Foggalong** [comment]
@erikdubois Is this actually not being fixed for you?

**Comment by erikdubois** [comment]
I will soon do a reinstall to test out the iso of Solus Mate.
I will remember to check it again.
Thanks

2016-11-04 0:32 GMT+01:00 Joshua H. Fogg <notifications@github.com>:

**Comment by erikdubois** [comment]
Ok tested it on linux mint 18 cinnamon.
The script's magic did it.
No worries.

2016-11-05 6:30 GMT+01:00 Erik Dubois <erik.dubois@gmail.com>:
