### ISSUE TITLE
DiscordCanary

### ISSUE THREAD

**Issue by M1sQ** [Foggalong/hardcode-fixer#281]
/usr/share/applications/DiscordCanary.desktop

[Desktop Entry]
Name=Discord Canary
Comment=All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
GenericName=Internet Messenger
Exec=/usr/bin/discord-canary
Icon=/usr/share/pixmaps/discord-canary.png
Type=Application
StartupNotify=true
Categories=Network;InstantMessaging;
StartupWMClass=discord

**Comment by erikdubois** [comment]
confirming need to change on arch linux budgie

looks like it is exactly the same

/usr/share/applications/DiscordCanary.desktop

[Desktop Entry]
Name=Discord Canary
Comment=All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
GenericName=Internet Messenger
Exec=/usr/bin/discord-canary
Icon=/usr/share/pixmaps/discord-canary.png
Type=Application
StartupNotify=true
Categories=Network;InstantMessaging;
StartupWMClass=discord
