### ISSUE TITLE
KeePass2 Plugin Application Indicator

### ISSUE THREAD

**Issue by diogo-gomes** [Foggalong/hardcode-fixer#299]
**Package:** keepass2-plugin-application-indicator

**Distribution:** Xubuntu 16.04

**Comment by Foggalong** [comment]
Hey! We need the `.desktop` filename from `/usr/share/applications/` and the icon line of that same file :)

**Comment by diogo-gomes** [comment]
Hi,

It is an indicator (don't have .desktop file in user/share/applications).

I'm using it on XFCE4 Indicator Plugin

**Comment by Foggalong** [comment]
Oh right, I think you've misunderstood what this program is for then. This script fixes application launchers not tray icons; that's covered by [hardcode-tray](https://github.com/bil-elmoussaoui/Hardcode-Tray)

**Comment by diogo-gomes** [comment]
Sorry, you've right. I misunderstood this script with hardcode-tray. Thanks
