### ISSUE TITLE
Do extensions hardcode?

### ISSUE THREAD

**Issue by Foggalong** [Foggalong/hardcode-fixer#305]
It's been the long held wisdom that having an extension in an icon line (e.g. `Icon=name.png` rather than `Icon=name`) hardcodes that icon. However I've just come across the case of RecordMyDesktop. It has the extension in the icon line but it's still quite clearly using the Numix icon.

![screenshot_2017-09-04_23-41-13](https://user-images.githubusercontent.com/5920259/30053612-55e524ae-9221-11e7-8214-22504baedcba.png)

Maybe this doesn't actually hardcode icons and we've just assumed it did, or maybe something has changed? Either way it calls into question whether we should be fixing these because, while the extension is unnecessary, it doesn't seem to be causing any problems.

**Comment by bil-elmoussaoui** [comment]
The freedesktop icon lookup algorithm can be found here https://standards.freedesktop.org/icon-theme-spec/latest/ar01s05.html
I don't think this causes any issues at all, as the algorithm looks for the icon with all the possible supported extensions (svg, png, xpm)
But anyway, i think this should be fixed to avoid possibles issues

**Comment by Foggalong** [comment]
In the rewrite I've been detecting launchers hardcoded like that by looking for a `.` in the icon line. However it's occurred to me that it doesn't allow for cases like the elementary apps where the icon lines are `Icon=com.github.dev.app`.

However if svg, png, and xpm are definitely the only supported icon extensions then rather than looking for `.` we can look for icon lines ending in those.

**Comment by bil-elmoussaoui** [comment]
It's not only elementary who uses that, GNOME too. And other distros will use that soon; it's a freeesktop standard that helps avoid having two apps called music, with the same desktop file and the same icon name. But with this new standard, both will have different icon name, and different desktop file as they follow the xxx.xxx.myapp

**Comment by Foggalong** [comment]
Yeah it sounds like it's a change for the better, I was just trying to work out how to account for it in the rewrite

**Comment by Foggalong** [comment]
@bil-elmoussaoui It would seem that svg, png, xpm aren't the only extensions that can be used: in testing I've come across and ico also. Is there going to be a way to differentiate an icon line like `Icon=app.ext` from `Icon=dev.app`? Is it even worth fixing if it's not actually causing any problems :confused:

**Comment by bil-elmoussaoui** [comment]
By looking at the source code of freedesktop icons location algorithm you can see that the supported extensions are only svg, png, xpm. If people are using other extensions, it's a different story... You can just split the icon name by "." And get the latest element and see if its one of the three extensions

**Comment by Foggalong** [comment]
Yeah I saw that. They might be the only officially supported extensions but they're clearly not the only ones being used by developers. The example I've found using an ico file is working without any problems in the lookup so it would still need to be accounted for in the same way. And if devs are using ico whose to say there aren't those using jpg or others?

**Comment by bil-elmoussaoui** [comment]
i have never seen any application using ico or jpg ;p what what that application?

**Comment by Foggalong** [comment]
A tool from a phone company for unlocking their phones. The icon lookup seem to be having no problems with it and it's showing up just fine in all the launchers.

![screenshot_2017-09-05_14-14-36](https://user-images.githubusercontent.com/5920259/30062856-8f1ef5d8-9244-11e7-8746-07fcad4b28b5.png)

**Comment by bil-elmoussaoui** [comment]
Ah :p well, in that case just ignore the extensions 👍

**Comment by Foggalong** [comment]
I'm an idiot and I've been testing the wrong thing. The icon lookup can handle it fine when it's the full location (e.g. `Icon=/path/to/app.ico`) but if the icon line is correct and the hicolor icon is in ico format then the lookup breaks. Playing around now to see if I can get it to show up by changing the extension to `png`.

**Comment by Foggalong** [comment]
Yeah, can't get the icon to show up just by changing the extension. This also means that the current version of the script wouldn't work with this app either since the ico copied to hicolor isn't being picked up. Will have a think about how to address this :confused:

**Comment by bil-elmoussaoui** [comment]
Well, in that case you can do anything about that. unless you add a convert function that will convert ico icon to a png. You can use imagemagick (which is installed in almost every linux system or available in the distro anyway). And using `convert image.ico image.png` This way, the icon will still work on the fallback theme

**Comment by Foggalong** [comment]
That could work, but would have to add cases for converting other invalid formats like jpg too. Will look into this, though because it was broken in the current version also I won't fix it from the get go in the redesign.

**Comment by Foggalong** [comment]
@bil-elmoussaoui To go back to the original case of this issue (whether to still fix icon lines of the format `Icon=app.png` even though it causes no issues) are you thinking that we should?

**Comment by bil-elmoussaoui** [comment]
It's really up to you, i always fix those icons even if they have an extension (manually sometimes); it's better to fix them i guess
