### ISSUE TITLE
New Mathematica windows in Gnome have hardcoded icos

### ISSUE THREAD

**Issue by jose-a-sa** [Foggalong/hardcode-fixer#308]
Hi,
I don't know if is it possible to include Mathematica in the supported applications of the hardcode-fixer ?
Every time I launch a new window it uses a pixelated icon in the image. If I remember correctly this does not occur when using unity desktop.
Regards, José

![screenshot from 2017-10-06 17-50-41](https://user-images.githubusercontent.com/13206784/31288977-08a4b518-aabf-11e7-901a-d704655bf7d3.png)

**Comment by bil-elmoussaoui** [comment]
Do you see the right icon on the gnome dash (the list of apps)?

**Comment by jose-a-sa** [comment]
Yes, I see the standard Numix icon version in the list of apps

**Comment by bil-elmoussaoui** [comment]
In this case, it's not a hardcoded icon issue. The desktop file shipped by Mathematica seems to lack the StartupWMClass which is used to identify the window with the correct desktop file and so show the correct icon. You can fix that using this script https://github.com/bil-elmoussaoui/StartupWMClassFixer (thanks God you can change anything on Linux :p) 
I don't think that they support Mathematica at the moment, but i will be waiting for a PR ;) 
The readme explains how to get the correct StartupWMClass using xprop
