### ISSUE TITLE
Question about the next version

### ISSUE THREAD

**Issue by SmartFinn** [Foggalong/hardcode-fixer#309]
Hi,

I want to help with [Next](https://github.com/Foggalong/hardcode-fixer/projects/1), so I should clearly understand how you guys want to implement it.

I have made a pseudo-UML diagram to show how I see it:

![hardcode-fixer-base](https://user-images.githubusercontent.com/819186/31327093-79983db8-acd5-11e7-9e07-3d691a85aa21.png)

**Comment by Foggalong** [comment]
I think that's roughly correct, but I'm gonna make some changes to the way it works probably reincorporating a CSV again to fix a few problems that @bil-elmoussaoui brought up.

**Comment by SmartFinn** [comment]
@Foggalong what changes of CSV do you mean? I know what we can delete unneeded entries like:

1. Delete all Steam rows
2. Delete rows with different name of desktop files
3. Delete rows with "hardcoded" extensions
4. Delete rows with icon_name that can be translated from app_name (`2048 Qt` → `2048-qt`)
5. Delete columns Launcher and Path

I already did all necessary functions for the program, need to compose it and create a CLI.

Btw, I'm used advanced bash scripting patterns, hope this not a problem.

**Comment by Foggalong** [comment]
Will close this since the questions asked about the next version were answered (bar the question about CSV, the response to which is the compliment of the rows which match what you listed)
