### ISSUE TITLE
Problem snap

### ISSUE THREAD

**Issue by rty45** [Foggalong/hardcode-fixer#310]
I added in my test global_apps= /var/lib/snapd/desktop/applications/

and new rules in tofix.csv 

VLC media player,vlc_vlc,/snap/vlc/4/meta/gui/vlc.png,vlc  

Everything works.

But there is a problem in frequently changing the way in constant snap updates:

Yesterday

Icon=/snap/vlc/3/meta/gui/vlc.png

Today

Icon=/snap/vlc/4/meta/gui/vlc.png   Etc. 

It's simply impossible to add a new rule to tofix.csv all the time.

**Comment by bil-elmoussaoui** [comment]
This should be reported upstream to snap devs. It can be fixed by hardcode fixer. But snap should really at least follow freedesktop guidelines and avoid hardcoding stuff...

**Comment by rty45** [comment]
I need your advice

The command added to the script:

find /home/${SUDO_USER:-$USER}/.local/share/applications/ /var/lib/snapd/desktop/applications/ -name '*.desktop' -exec sed -ri 's|^(Icon=)/snap.*|\1|' {} +

and rules in tofix.csv: 

AnimationMaker,animationmaker_animationmaker,,animationmaker-snap
Archaeopteryx,archaeopteryx_archaeopteryx,,archaeopteryx-snap
Atom,atom_atom,,atom-snap
Atomify LAMMPS,atomify_atomify,,atomify-snap
Audovia,audovia_Audovia,,audovia-snap
B1 Free Archiver,b1freearchiver_b1,,b1-snap
Balloon Pop,balloon-pop_snap,,balloon-pop-snap
Baugeschichte,baugeschichte_baugeschichte,,baugeschichte-snap
Bayam,bayam_bayam,,bayam-snap
BitTicker,bitticker_bitticker,,bittickerlogo-snap

solved the snap problem. But it's too rude.

All not known to me and not registered in the tofix.csv snap.desktop will be without icons.

Is it possible to limit the application of the script solely to a separate list of known snap.desktop - tofix-snap.csv:

animationmaker_animationmaker
archaeopteryx_archaeopteryx
atom_atom
atomify_atomify
audovia_Audovia
b1freearchiver_b1
balloon-pop_snap
baugeschichte_baugeschichte
bayam_bayam
bitticker_bitticker

To protect all new snap.desktop from damage

What should I add to the script?
It's just for me. On the test.

**Comment by Foggalong** [comment]
Well that's shit. I didn't realise snaps were doing this :/

**Comment by bil-elmoussaoui** [comment]
@Foggalong This can be closed. The issue could be fixed either by upstream or once we have a correct fix for the hardcoded non-static icons paths

**Comment by LyzardKing** [comment]
The latest installed version of a snap is in /snap/vlc/current/...
Could that be used in the fix rule? It's a symlink to the actual version(3 or 4 in the vlc case)
