### ISSUE TITLE
TeamSpeak 3

### ISSUE THREAD

**Issue by bil-elmoussaoui** [Foggalong/hardcode-fixer#311]
| Application name | Icon name | Desktop file name |
| --- | :-- | :-- |
| TeamSpeak 3 | `teamspeak3.xpm` | `teamspeak3.desktop` |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by SmartFinn** [comment]
@bil-elmoussaoui but this icon name is not hardcoded :confused:

**Comment by bil-elmoussaoui** [comment]
The extension is, i'm just trying to figure out how to add hardcode-fixer support into IconRequests :D 
The icon extension shouldn't be added into the icon line at all...

**Comment by SmartFinn** [comment]
@bil-elmoussaoui 

> The icon extension shouldn't be added into the icon line at all...

but it works with teamspeak3.{png,svg,svgz} icon... Didn't see any sense to fix it.
