### ISSUE TITLE
LSHW support

### ISSUE THREAD

**Issue by varlesh** [Foggalong/hardcode-fixer#325]
Site: https://ezix.org/project/wiki/HardwareLiSter

Package from Manjaro repo: http://mirror.inode.at/manjaro/stable/community/x86_64/lshw-B.02.18-2-x86_64.pkg.tar.xz

**Desktop**:
```
[Desktop Entry]
Name=LSHW
Comment=HardWare LiSter
Comment[fr]=Listeur de matériel
Comment[es]=Listar equipamiento
Categories=Application;System;X-Red-Hat-Base;X-Fedora;
Icon=/usr/share/lshw/artwork/logo.svg
Exec=/usr/sbin/gtk-lshw
Type=Application
Terminal=false
Encoding=UTF-8
X-Desktop-File-Install-Version=0.10
```
icon `lshw` or `gtk-lshw`

**Comment by bilelmoussaoui** [comment]
What's the desktop file name?

**Comment by varlesh** [comment]
`/usr/share/applications/gtk-lshw.desktop`
