### ISSUE TITLE
Mint applications not hardcoded anymore (Linux Mint 18.3)

### ISSUE THREAD

**Issue by NikoKrause** [Foggalong/hardcode-fixer#329]
Hey,

just found your script. I think the idea is pretty cool.
I watched at your list: https://github.com/Foggalong/hardcode-fixer/blob/master/tofix.csv
and noticed that Mint applications are in there as well.
Since I'm on Linux Mint 18.3, I checked:
* Mint Backup
* Mint Drivers
* Mint Nanny
* Mint Software Center
* Mint Update Manager
* Mint Upload Manager

Those have no hardcoded icons anymore. When I change the icon theme, those icons change in the menu. So I guess, they can be removed from the list.

**Comment by Foggalong** [comment]
@NikoKrause We don't remove entries from the list - they won't be changed if they're not hardcoded anymore and this way we retain compatibility with older distributions.
