### ISSUE TITLE
Support for Papyrus

### ISSUE THREAD

**Issue by patzj** [Foggalong/hardcode-fixer#340]
After running the hardcode-fixer and restarting the machine, Slack icon didn't changed on the taskbar. Please add support to [Papyrus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) icon theme.

```[Desktop Entry]
Name=Slack
Comment=Slack Desktop
GenericName=Slack Client for Linux
Exec=/usr/bin/slack %U
Icon=slack
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Network;InstantMessaging;
MimeType=x-scheme-handler/slack;
```

**Comment by SmartFinn** [comment]
The launcher is already fixed. Do you sure that is not a Papirus icon? They look very similar.

> Slack icon didn't changed on the taskbar.

Probably, that is because of the desktop-file missing `StartupWMClass` option. The icon in the menu and in the taskbar have different icons?

**Comment by Foggalong** [comment]
Yeah that's not a hardcoded launcher. The problem will either be on Papirus' end or some other component of the desktop.

**Comment by patzj** [comment]
The snippet was after I ran hardcode-fixer. I'll checkout this `StartupWMClass` thing from @SmartFinn's comment. Thank you.
