### ISSUE TITLE
masterpdfeditor5

### ISSUE THREAD

**Issue by erikdubois** [Foggalong/hardcode-fixer#349]
| Application name | Icon name | Desktop file name |
| --- | :-- | :-- |
|  masterpdfeditor5 | Icon=/opt/master-pdf-editor-5/masterpdfeditor5.png | masterpdfeditor5.desktop |

advice to change to masterpdfeditor5

**Comment by Foggalong** [comment]
This is already [in the file](https://github.com/Foggalong/hardcode-fixer/blob/master/tofix.csv#L235)!
