### ISSUE TITLE
Fix 'MyNotes'

### ISSUE THREAD

**Issue by NusryNizam** [Foggalong/hardcode-fixer#356]
| Application name | Icon name | Desktop file name |
| --- | :-- | :-- |
| MyNotes | `mynotes` | `MyNotes` |

link: https://github.com/j4321/MyNotes/

**Comment by Foggalong** [comment]
This isn't a hardcoded icon! If it's not showing up as themed for you that just means whatever icon theme you're using doesn't have a mynotes icon :slightly_smiling_face:
