### ISSUE TITLE
PDF2PNG

### ISSUE THREAD

**Issue by tiotrom** [Foggalong/hardcode-fixer#365]
| pdf2png | Icon=/usr/share/pixmaps/pdf2png.png | pdf2png.desktop |

**Comment by tiotrom** [comment]
Same.... /usr/share/pixmaps/pdf2png.png is the correct path that you added, but it cannot grab the pdf2png.svg icon from our icon pack. I am wondering if there is anything wrong on our end. Some icons like Tixati work, but many do not...

**Comment by Foggalong** [comment]
@tiotrom Got a repo for it? Happy to take a look!

**Comment by tiotrom** [comment]
Not yet, we are working on that. We are using https://github.com/zayronxio/Zafiro-icons + our own custom icons from here - https://www.cloud.tromsite.com/s/SQ9XkLnDkbnZKSx. Install the Zafiro icon pack, then please copy the icons from there to 
![image](https://user-images.githubusercontent.com/34804533/92326631-e0a3bb80-f053-11ea-9e3f-28c1a4fefd4b.png)

Let me know how we could help out.
