### ISSUE TITLE
ClipGrab

### ISSUE THREAD

**Issue by tiotrom** [Foggalong/hardcode-fixer#366]
| ClipGrab | Icon=/usr/share/pixmaps/clipgrab.png | clipgrab.desktop |

**Comment by Foggalong** [comment]
Duplicate of #43

**Comment by tiotrom** [comment]
For me this one does not work. I checked the paths. Everything is correct.
Icon=/usr/share/pixmaps/clipgrab.png
Yet it does not grab the clipgrab.svg icon from our icons set.
