### ISSUE TITLE
Icon request: TeXstudio

### ISSUE THREAD

**Issue by melancholyaeon** [Foggalong/hardcode-fixer#368]
TeXstudio (https://texstudio.org/) has a very ugly native icon. /usr/share/texstudio/texstudio128x128.png
![texstudio16x16](https://user-images.githubusercontent.com/66167854/83328442-64931e00-a283-11ea-89c2-9e71369be4d1.png)

Please make a lovely  Papirus-Light icon for us all so we don't have to hate looking at our panels quite so much. Ty!

**Comment by Foggalong** [comment]
To just to be clear, I don't make icons in this repo it's just a script that fixes the launchers so that if a theme does have an icon it shows up properly :)
