### ISSUE TITLE
Menu Whisker

### ISSUE THREAD

**Issue by xdursoc** [Foggalong/hardcode-fixer#370]
The Whisker Menu icon is unthemable, I tried to use the fix.sh script but the icon is still without theme.
Debian 10 with XFCE.

**Comment by Foggalong** [comment]
I'll double check this, but if my XFCE knowledge serves me right I think the Whisker Menu icon is related to a panel setting rather than a `.desktop` launcher (so would be outside the ability of this script to fix).

**Comment by Foggalong** [comment]
Some DEs do actually provide a launcher for this, but looking around source repos none of them seem to be hardcoded so I'm guessing your particular issue is to do with changing it in the XFCE settings instead. Let me know if that's not the case and I'll update here :)
