### ISSUE TITLE
Can't execute

### ISSUE THREAD

**Issue by olddesklamp** [Foggalong/hardcode-fixer#408]
Can't execute the script due to a syntax error.

```
josh@mercury:~/Downloads/git/hardcode-fixer$ sudo sh fix.sh
fix.sh: 19: Syntax error: "(" unexpected
josh@mercury:~/Downloads/git/hardcode-fixer$ 
```

I just cloned the script minutes before submitting this issue. I'm running the script on Pop!_OS 22.04 using Bash 5.1.16.

**Comment by SmartFinn** [comment]
Try to replace the command  with `sudo bash fix.sh`. Posix shell (dash) is not supported.
