### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by adrummer354** [Foggalong/hardcode-fixer#409]
| Zoom | Zoom | Zoom |
| --- | :-- | :-- |
| Application name | `The Icon attribute in the desktop file` | `Desktop file name` |

**Comment by adrummer354** [comment]
I am not seeing the script fix the icon for the Zoom app for Linux Mint

**Comment by adrummer354** [comment]
Using XAppStatusApplet on Mint 20.3 with Cinnamon and Paprius Dark and Hardcorded tray icons and seeing this icon:

https://imgur.com/a/DUrXTIg

**Comment by Foggalong** [comment]
@adrummer354 Please provide the filename of the launcher and the icon line in that launcher, otherwise this can't be fixed!

**Comment by adrummer354** [comment]
I am not sure how to find this information. Where would it be?

**Comment by Foggalong** [comment]
@adrummer354 Usually in a place like `/usr/share/applications/` or `~/.local/share/applications/`

**Comment by adrummer354** [comment]
Thanks. I found this command to successfully run it:

/usr/bin/zoom %U

it was located in: /usr/share/applications

I am not sure were the icon line  would be located.

**Comment by Foggalong** [comment]
@adrummer354 No so within `/usr/share/applications` there should be a file called something like `zoom.desktop`. Within that file there's a line which begins `Icon=` - it's the name of the file and the contents of that line I need :)

**Comment by adrummer354** [comment]
Closing this issue anyway since  I've moved away from Mint 20.3 and onto 21.1 which I don't think supports this hardcode tray.

**Comment by Foggalong** [comment]
@adrummer354 Ah shoot, if it's hardcoded tray icons you want to fix you need [hardcode-tray](https://github.com/bilelmoussaoui/Hardcode-Tray). This repo is a tool for fixing hardcoded application launchers (like in the Mint start menu).
