### ISSUE TITLE
JetBrains software (IntelliJ, WebStorm)

### ISSUE THREAD

**Issue by zacpier** [Foggalong/hardcode-fixer#56]
The icons in JetBrains' software are hardcoded

**Comment by hlechner** [comment]
I've investigated on it. I search for the webstorm one.

It seems that there isn't inside Ubuntu package system or Fedora package system.

I found it on AUR, but the desktop file on AUR package is not hardcoded.

through the source code: http://download.jetbrains.com/webstorm/WebStorm-9.0.3.tar.gz, I didn't find any desktop file, the bash script for install the software doesn't create the file also.

@zacpier could you give the following information:
- The name of desktop file (normally is inside /usr/share/applications/)
- The full content of this file

Without this we can't help you further :(

**Comment by brodock** [comment]
please add RubyMine also to the list.
The desktop entry can be automatically generated by the running application by going to tools > create desktop entry menu.

Here is an example of the generated entry:

```
[Desktop Entry]
Version=1.0
Type=Application
Name=RubyMine
Icon=/opt/RubyMine-7.0.2/bin/RMlogo.svg
Exec="/opt/RubyMine-7.0.2/bin/rubymine.sh" %f
Comment=Develop with pleasure!
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-rubymine
```

/usr/local/share/applications/jetbrains-rubymine.desktop
