### ISSUE TITLE
Hardcode-fixer and Teamviewer 10

### ISSUE THREAD

**Issue by acutbal** [Foggalong/hardcode-fixer#61]
Hi!!

First of all, I apologize if here it's not the correct place or correct way to report, I'm not a designer or developer but I would like to help as Numix is a great thing. Today I've installed Teamviewer 10 (the last version launched recently) and ran hardcode-fixer, logout and log in to my session but it didn't worked.
This is the code for teamviewer-teamviewer10.desktop:
[Desktop Entry]
Version=1.0
Encoding=UTF-8
Name=TeamViewer 10
Comment=TeamViewer Remote Control Application
Exec=/opt/teamviewer/tv_bin/script/teamviewer
Icon=/opt/teamviewer/tv_bin/desktop/teamviewer.png
Type=Application
Categories=Network;
#Categories=Network;RemoteAccess;

I've found it on /opt/teamviewer/tv_bin/script/teamviewer.

Thank you very much for your work!! :smile:

**Comment by erikdubois** [comment]
just tested the script and teamviewer 10 is not willing to change
