### ISSUE TITLE
MediaElch hardcoded icon

### ISSUE THREAD

**Issue by matteosecli** [Foggalong/hardcode-fixer#64]
Hello, I've found another hardcoded-icon app: MediaElch. Their launcher (/usr/share/applications/MediaElch.desktop) says:

[Desktop Entry]
Encoding=UTF-8
Version=2.1
Type=Application
Terminal=false
Exec=/usr/bin/MediaElch
Name=MediaElch
Icon=/usr/share/pixmaps/MediaElch.png
Categories=Video;

I'm using the latest version (2.2) even if it says 2.1. I've also opened a bug report on their site to request a proper change in the .desktop file: http://community.kvibes.de/topic/show/mediaelch-icon-launcher

**Comment by hlechner** [comment]
Hi @matteosecli, sorry for look into your issue just now.

Thanks for open a request inside them bug report, but unfortunately it's closed and there is no answer on it.

Could you re-open the issue on their side?

Just to better explain to them:
- Yes, it just need to be the base name (without path or extension)
- It doesn't need to be done on deb's package specifically, it should reflect to all package, so just change into source code (/mediaelch-2.2.2/desktop/MediaElch.desktop) then reflect all others packages with this change :)

If remain questions, let me know!
