### ISSUE TITLE
hardcode fixer PR question

### ISSUE THREAD

**Issue by palob** [Foggalong/hardcode-fixer#67]
As far as I can see the fixing database is *totfix.svg*. I plan on arranging a PR in order to work off the backlog. 

Are there any precautions needed for applications with multiple hardcoded paths?

In contrary to the past assumption icons with a correct icon line aren't hardcoded even if stored in */usr/share/pixmaps*, right? In my experience theming works without further ado.

Another question: For launchers hardcoded to "Icon=iconname.png", is it of any help to create a Numix Circle icon "iconname.png.svg". Does this circumvent the hardcoding?
As far as I could examine it doesn't help.

**Comment by Foggalong** [comment]
For your first question, no precautions needed :) Look at "Gens GS" for an example

I'm not sure for your second question, but I think you're right that it doesn't

**Comment by palob** [comment]
Thanks, I'll start preparing the PR soon.
