### ISSUE TITLE
Nsight Eclipse Edition Hardcoded Icon

### ISSUE THREAD

**Issue by hlechner** [Foggalong/hardcode-fixer#68]
Inside [cuda](https://www.archlinux.org/packages/community/x86_64/cuda/) (nvidia) package there is the **Nsight Eclipse Edition** application who has the following hardcoded icon:
![image](https://cloud.githubusercontent.com/assets/11244067/6578200/81775b78-c721-11e4-9618-06b9ad95edf5.png)

**nsight.desktop**:
```
[Desktop Entry]
Type=Application
Name=Nsight Eclipse Edition
GenericName=Nsight Eclipse Edition
Icon=/opt/cuda/libnsight/icon.xpm
Exec=/opt/cuda/bin/nsight
TryExec=/opt/cuda/bin/nsight
Keywords=cuda;gpu;nvidia;debugger;
X-AppInstall-Keywords=cuda;gpu;nvidia;debugger;
X-GNOME-Keywords=cuda;gpu;nvidia;debugger;
Terminal=false
Categories=Development;IDE;Debugger;ParallelComputing;
```

**Comment by hlechner** [comment]
This app has a trouble on it: it's not standardized.

The installation place its totally different from Arch to Ubuntu for example.

And also from Ubuntu side the Nsight doesn't belongs to cuda package but from a separate package (nvidia-nsight).

Looking at the file list of ubuntu's package it's possible to see that there is no ".desktop" on it:
http://packages.ubuntu.com/trusty/amd64/nvidia-nsight/filelist

Maybe the best approach is to contact the Arch maintainers?

**Comment by Foggalong** [comment]
Yeah, sometimes it's the packager that introduces the problem. We've had a few from the AUR like it, and the Ubuntu Software Centre actually used to **require hardcoding** before it would ship the program. It's an uphill battle for sure.

**Comment by hlechner** [comment]
I've raised a bug report in Arch Bug Report:
https://bugs.archlinux.org/index.php?do=details&task_id=44294

It include this bug and also the bug #69 

Depend on answer that I'll receive there, I add the lines to tofix file or close the issues

**Comment by hlechner** [comment]
Bug closed on arch side. it came from the ".rpm" provided by nvidia.

So the problem is on nvidia side... and we know that nvidia don't  like to solve these hardcoded icons, same as nvidia-settings.
