### ISSUE TITLE
Civilization V hardcoded icon?

### ISSUE THREAD

**Issue by Plasmodium1** [Foggalong/hardcode-fixer#85]
Hi, I am using the Numix theme and the Civ V icon just appears as a generic Steam icon, despite there being a Numix icon for Civ V. I found a post in the Numix-circle github about this, but it just linked to here, where Civ is not on the supported apps list.

**Comment by hlechner** [comment]
We can add this game here so this script (hardcode-fixer) can fix it for you :)

But we need 2 information to add this game into our list:

- where is the location for the shortcut?
( example: /usr/share/applications/program_name.desktop )
-  what's the shortcut content?
( you can use *cat* in terminal, for example: *cat /usr/share/applications/program_name.desktop* )

Could you please provide it for us?

**Comment by Plasmodium1** [comment]
It's a Steam game - does that mean its shortcut is kept somewere else? I can't find it in the "/usr/share/applications/" folder...

**Comment by Plasmodium1** [comment]
There is one in /home/USER/.steam/steam/steamapps/common/Sid Meier's Civilization V/Civ5XP, but double-clicking it doesn't seem to launch it...

**Comment by hlechner** [comment]
Yes, to show it in your desktop, it needs to be in somewhere in your computer.

the most common path are:
- /usr/share/applications/ (that you have already checked)
- /home/USER/.local/share/applications/
- /home/USER/Desktop/

Could you check in these paths?

**Comment by Plasmodium1** [comment]
Thanks, I found it just before you posted that! ;-)

It is here: /home/USER/.local/share/applications/Sid Meier's Civilization V.desktop

This is the contents of the file:
[Desktop Entry]
Name=Sid Meier's Civilization V
Comment=Play this game on Steam
Exec=steam steam://rungameid/8930
Icon=steam
Terminal=false
Type=Application
Categories=Game;

**Comment by hlechner** [comment]
Yea, thanks!

I'll submit a new pull request with this one, when merged it will repair your shortcut too.

**Comment by Plasmodium1** [comment]
Thanks!

**Comment by Plasmodium1** [comment]
That's worked brilliantly. Cheers, guys!
