### ISSUE TITLE
Hardcoding report

### ISSUE THREAD

**Issue by PGPereira** [Foggalong/hardcode-fixer#96]
Please, fix Firefox Developer and Visual Studio Code.

**Comment by palob** [comment]
Could you please tell the names of the .desktop launcher files and the icon lines in those files?

**Comment by PGPereira** [comment]
Apparently they fixed the firefox-developer desktop icon. The .desktop is located at /usr/share/applications/visual-studio-code.desktop and contains:

[Desktop Entry]
Categories=Development;
Exec=/usr/bin/visual-studio-code
Icon=visual-studio-code
Terminal=false
Type=Application
Name=Visual Studio Code
Comment=Editor for building and debugging modern web and cloud applications

**Comment by palob** [comment]
It isn't hardcoded actually. Numix Circle just needs a symlink :)

**Comment by Foggalong** [comment]
Added the symlink in Circle :)

**Comment by PGPereira** [comment]
Thank you.
